### ISSUE TITLE
Primitives marked as virtual and not redefined in global do not show as compilation errors but prevent model from running

### ISSUE THREAD

**Issue by AlexisDrogoul** [gama-platform/gama.old#3492]
**Describe the bug**
If a model (`global`) is marked as implementing a skill that defines a `virtual` action (i.e. that should be redefined) without redefining it, it compiles correctly but generates an error when trying to run it. 

**To Reproduce**
1. Open (for instance) `GAML Syntax > System > RunThread.gaml`
2. remove the definition of `thread_action` in `global`
3. try to run the model (nothing happens)

**Error*
A compilation error appears in the Java console : 
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.ecore.EObject.eResource()" because the return value of "msi.gaml.descriptions.ActionDescription.getUnderlyingElement()" is null
	at msi.gaml.descriptions.ModelDescription.finalizeDescription(ModelDescription.java:519)
	at msi.gaml.factories.ModelAssembler.assemble(ModelAssembler.java:163)
	at msi.gaml.factories.ModelFactory.createModelDescription(ModelFactory.java:61)
	at msi.gama.lang.gaml.resource.GamlResource.buildModelDescription(GamlResource.java:222)
	at msi.gama.lang.gaml.resource.GamlResource.buildCompleteDescription(GamlResource.java:256)
	at msi.gama.lang.gaml.resource.GamlResource.validate(GamlResource.java:283)
	at msi.gama.lang.gaml.validation.GamlResourceValidator.validate(GamlResourceValidator.java:62)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:92)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob$1.exec(ValidationJob.java:1)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.util.concurrent.WrappingCancelableUnitOfWork.exec(WrappingCancelableUnitOfWork.java:58)
	at org.eclipse.xtext.util.concurrent.CancelableUnitOfWork.exec(CancelableUnitOfWork.java:27)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:70)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:525)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:497)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:136)
	at org.eclipse.xtext.util.concurrent.IReadAccess.tryReadOnly(IReadAccess.java:50)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.createIssues(ValidationJob.java:87)
	at org.eclipse.xtext.ui.editor.validation.ValidationJob.run(ValidationJob.java:68)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Desktop (please complete the following information):**
 - GAMA version: 1.8.2
 - Java version: 17

**Comment by AlexisDrogoul** [comment]
Problem has been fixed and tested
