### ISSUE TITLE
Potential issue using Headless mode with Socket on Windows

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.old#3497]
**Describe the bug**
I am not sure if this is the right place to post this issue (and if it's an issue) but I find a problem using the client (javascript client) / server (Gama Headless) architecture on Windows.

The architecture work well with Ubuntu/Mac OS but I have the following error thrown by GAMA when I "plug" my JS client to Gama headless Server using windows

````
C:\Users\VCity\Documents\Github\UD_ReAgent_ABM\ReAgent\models\Gratte_Ciel_Demo.gaml model is being compiled...
java.lang.Exception: java.lang.NoClassDefFoundError: org/eclipse/core/resources/ResourcesPlugin
        at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1093)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/core/resources/ResourcesPlugin
        at msi.gama.lang.gaml.indexer.GamlResourceIndexer.<clinit>(GamlResourceIndexer.java:52)
        at msi.gama.lang.gaml.resource.GamlResource.doLinking(GamlResource.java:325)
        at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:304)
        at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:292)
        at msi.gama.lang.gaml.resource.GamlResource.updateInternalState(GamlResource.java:255)
        at org.eclipse.xtext.resource.XtextResource.doLoad(XtextResource.java:182)
        at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLoad(LazyLinkingResource.java:115)
        at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
        at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
        at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:266)
        at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:33)
        at msi.gama.lang.gaml.validation.GamlModelBuilder.buildModelDescription(GamlModelBuilder.java:111)
        at msi.gama.lang.gaml.validation.GamlModelBuilder.compile(GamlModelBuilder.java:97)
        at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:154)
        at msi.gama.headless.core.HeadlessSimulationLoader.loadModel(HeadlessSimulationLoader.java:125)
        at msi.gama.headless.job.ManualExperimentJob.load(ManualExperimentJob.java:87)
        at msi.gama.headless.job.ManualExperimentJob.loadAndBuildWithJson(ManualExperimentJob.java:95)
````

**To Reproduce**
The idea is to have a client running and listening to Gama server on the same port
One documented example of how to run it can be found here https://github.com/VCityTeam/UD_ReAgent_ABM

**Expected behavior**
Working in the same way as Mac and Linux

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by lesquoyb** [comment]
@hqnghi88 and @agrignard what are the updates on this bug ? There has been a lot of changes in gama-server since it was opened. Is it solved or still impossible to run this on windows ?

**Comment by hqnghi88** [comment]
I cant test on win this week (no machine) but i will see and update the syntax to adapt with new gama-server first.

**Comment by lesquoyb** [comment]
@hqnghi88 any update ?

**Comment by agrignard** [comment]
Hi @lesquoyb I will close this issue as apparently it was on a specific machine that didn't get the admin right when calling the headless mode. I cannot test it by myself as I don't have access to this machine anymore. I will reopen this issue  if it rehappens
