### ISSUE TITLE
When an error happen in GamaServer, the simulation keeps trying to run steps

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3506]
**Describe the bug**
When running an experiment in gama-server and an error occurs, gama-server does not destroy the experiment and keeps trying to run the next step of the experiment.

**To Reproduce**
1. run gama-server
2. ask for this model to be run:
```
model error_test

global {
	
	reflex t {
		list l;
		write l[1];
	}
}

experiment a {}
```
3. the server keeps printing the exception:
```
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
Java error: index out of bounds
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:71)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:97)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.statements.WriteStatement.privateExecuteIn(WriteStatement.java:96)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.runtime.IScope.execute(IScope.java:410)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:90)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.runtime.IScope.execute(IScope.java:410)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:112)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:205)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:242)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:535)
	at msi.gama.common.interfaces.IScopedStepable.step(IScopedStepable.java:27)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at msi.gama.util.IList.get(IList.java:370)
	at msi.gama.util.GamaList.getFromIndicesList(GamaList.java:115)
	at msi.gaml.operators.Containers.internal_at(Containers.java:554)
	at gaml.additions.core.GamlAdditions.lambda$504(GamlAdditions.java:562)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:93)
	... 27 more
...
```
4. As a side effect, the client too gets spammed by error messages
![image](https://user-images.githubusercontent.com/6374469/195038684-23969a83-0431-41ec-b212-757200357141.png)

**Expected behavior**
Once an exception occurs in the running experiment, it is raised once and the experiment closes properly

**Comment by AlexisDrogoul** [comment]
You should probably look into the preferences: one is explicitly instructing GAMA to stop at first error or not, and maybe its value under GamaServer is not correct ?

**Comment by hqnghi88** [comment]
Yes we should check that pref and i need to verify if headless mode take it into account.

**Comment by lesquoyb** [comment]
There is a parameter "Stop simulation at first error" set to true in my Gama settings, so I guess it's just not taken into account in server mode
