### ISSUE TITLE
GamaRuntimeException are thrown multiple times

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3507]
**Is your request related to a problem? Please describe.**
When a runtime exception happens in a running experiment, the exception thrown multiple times instead of once.
This seems like nothing, but in server mode it leads to as many error messages sent for the same experiment which in my point of view is all but clean for the client.

**To Reproduce**
1. From eclipse run gama
2. run this model:
```
model error_test

global {
	
	reflex t {
		list l;
		write l[1];
	}
}

experiment a {}
```
3. See in the console that the error has been reported and thrown multiple times instead of just once:
```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at msi.gama.util.IList.get(IList.java:370)
	at msi.gama.util.GamaList.getFromIndicesList(GamaList.java:115)
	at msi.gaml.operators.Containers.internal_at(Containers.java:554)
	at gaml.additions.core.GamlAdditions.lambda$514(GamlAdditions.java:572)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:93)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.statements.WriteStatement.privateExecuteIn(WriteStatement.java:96)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.runtime.IScope.execute(IScope.java:410)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:90)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.runtime.IScope.execute(IScope.java:410)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:112)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:205)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:242)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:535)
	at msi.gama.common.interfaces.IScopedStepable.step(IScopedStepable.java:27)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
reportAndThrowIfNeeded : Java error: index out of bounds
report error : Java error: index out of bounds
Java error: index out of bounds
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:71)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:97)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.statements.WriteStatement.privateExecuteIn(WriteStatement.java:96)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.runtime.IScope.execute(IScope.java:410)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:90)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.runtime.IScope.execute(IScope.java:410)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:112)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:205)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:242)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:535)
	at msi.gama.common.interfaces.IScopedStepable.step(IScopedStepable.java:27)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at msi.gama.util.IList.get(IList.java:370)
	at msi.gama.util.GamaList.getFromIndicesList(GamaList.java:115)
	at msi.gaml.operators.Containers.internal_at(Containers.java:554)
	at gaml.additions.core.GamlAdditions.lambda$514(GamlAdditions.java:572)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:93)
	... 27 more
 ```

**Describe the improvement you'd like**
The exception is only thrown once.

**Describe alternatives you've considered**
If we ignore the fact that eclipse's console is also spammed, we could filter the message sent in the gama-server part, but I find that way dirtier as it's just a workaround.

**Additional context**
As an example, here is what a client that connects to the server, load the faulty experiment written above, then run it receives:
![image](https://user-images.githubusercontent.com/6374469/196080748-dd2d027d-2c22-4a21-8f7c-b2aeeb711c79.png)

**Comment by AlexisDrogoul** [comment]
I have pushed a possible solution (it was actually very simple).

**Comment by lesquoyb** [comment]
Tested, it works
