### ISSUE TITLE
Error when reading a tif file

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3523]
**Describe the bug**
The following attempts to read a tif file and to define the envelope of the world with it.
I get an error at execution. 
This code with these data was working fine a few months ago.

I get the following error in GAMA:
```
1 occurence in Simulation 0 at cycle 0: The format of Patchwork_WL_201810150430.tif seems incorrect: Could not initialize class it.geosolutions.imageioimpl.plugins.tiff.gdal.GDALMetadataParser
in geometry shape <- envelope(Patchwork_WL_) ;
when applying the envelope operator on msi.gama.util.file.GamaGridFile@2e504245
in initializing attribute shape
in agent Simulation 0
```

Note that in Eclipse, I get the following one:
```
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NoClassDefFoundError: Could not initialize class it.geosolutions.imageioimpl.plugins.tiff.gdal.GDALMetadataParser
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.initializeFromMetadata(TIFFImageReader.java:1303)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.seekToImage(TIFFImageReader.java:831)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.seekToImage(TIFFImageReader.java:788)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.prepareRead(TIFFImageReader.java:1586)
	at it.geosolutions.imageioimpl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1780)
	at java.desktop/javax.imageio.ImageReader.read(ImageReader.java:938)
	at ummisco.gama.ui.metadata.ImageDataLoader.readTiff(ImageDataLoader.java:162)
	at ummisco.gama.ui.metadata.ImageDataLoader.getImageData(ImageDataLoader.java:93)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.createImageFileMetaData(FileMetaDataProvider.java:546)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.lambda$0(FileMetaDataProvider.java:403)
	at ummisco.gama.ui.metadata.FileMetaDataProvider.getMetaData(FileMetaDataProvider.java:439)
	at ummisco.gama.ui.navigator.contents.ResourceManager.processAddition(ResourceManager.java:371)
	at ummisco.gama.ui.navigator.contents.ResourceManager.visit(ResourceManager.java:564)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
	at ummisco.gama.ui.navigator.contents.ResourceManager.resourceChanged(ResourceManager.java:320)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:297)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:160)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:388)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1514)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2394)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.ui.ide.undo.AbstractWorkspaceOperation.execute(AbstractWorkspaceOperation.java:200)
	at org.eclipse.ui.actions.CopyFilesAndFoldersOperation.performCopy(CopyFilesAndFoldersOperation.java:1258)
	at org.eclipse.ui.actions.CopyFilesAndFoldersOperation.copyResources(CopyFilesAndFoldersOperation.java:1773)
	at org.eclipse.ui.actions.CopyFilesAndFoldersOperation.lambda$1(CopyFilesAndFoldersOperation.java:608)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**To Reproduce**
1. Import the following model and launch it.
[TestTiFF.zip](https://github.com/gama-platform/gama/files/9907652/TestTiFF.zip)

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - GAMA version: git (1.8.2)
 - Java version: 17

**Comment by benoitgaudou** [comment]
Thx that seems to work !
