### ISSUE TITLE
Error due to the console when relaunching a simulation

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3524]
**Describe the bug**
I run a model that write in the console some messagaes.
When I relaunch it (click on the button in the Simulation perspective), I sometimes get the following error.

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.ui.console.IOConsole.newOutputStream()" because "this.msgConsole" is null
	at ummisco.gama.ui.views.console.ConsoleView.getWriterFor(ConsoleView.java:101)
	at ummisco.gama.ui.views.console.ConsoleView.append(ConsoleView.java:148)
	at ummisco.gama.ui.views.console.ConsoleView.append(ConsoleView.java:135)
	at ummisco.gama.ui.factories.ConsoleDisplayerFactory$ConsoleDisplayer.writeToConsole(ConsoleDisplayerFactory.java:85)
	at ummisco.gama.ui.factories.ConsoleDisplayerFactory$ConsoleDisplayer.informConsole(ConsoleDisplayerFactory.java:63)
	at msi.gaml.statements.WriteStatement.privateExecuteIn(WriteStatement.java:104)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.runtime.IScope.execute(IScope.java:410)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:90)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:498)
	at msi.gama.runtime.IScope.execute(IScope.java:439)
	at msi.gama.runtime.IScope.execute(IScope.java:410)
	at msi.gaml.architecture.reflex.ReflexArchitecture.init(ReflexArchitecture.java:137)
	at msi.gama.metamodel.agent.AbstractAgent.init(AbstractAgent.java:166)
	at msi.gama.metamodel.agent.MinimalAgent._init_(MinimalAgent.java:258)
	at msi.gama.kernel.simulation.SimulationAgent._init_(SimulationAgent.java:387)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:223)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:590)
	at msi.gama.metamodel.agent.AbstractAgent.schedule(AbstractAgent.java:295)
	at msi.gama.kernel.simulation.SimulationAgent.schedule(SimulationAgent.java:366)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:167)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:121)
	at msi.gama.metamodel.population.IPopulation.createAgents(IPopulation.java:229)
	at msi.gama.kernel.experiment.ExperimentAgent.createSimulation(ExperimentAgent.java:363)
	at msi.gama.kernel.experiment.ExperimentAgent._init_(ExperimentAgent.java:321)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:223)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:339)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:590)
	at msi.gama.kernel.experiment.ExperimentController.schedule(ExperimentController.java:280)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:386)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:673)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:713)
	at msi.gama.kernel.experiment.ExperimentPlan.reload(ExperimentPlan.java:719)
	at msi.gama.kernel.experiment.ExperimentController.processUserCommand(ExperimentController.java:153)
	at msi.gama.kernel.experiment.ExperimentController.lambda$1(ExperimentController.java:68)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
1. I get it with some "big" models, as an example the one provided with message  #10519 of the diffusion list.
2. I run the debug experiment
3. relaunch it from the simulation perspective.
 

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - GAMA version:git
 - Java version: 17

**Comment by benoitgaudou** [comment]
To complete the previous issue, here is a simpler model on which I have this issue:
[TestConsole.zip](https://github.com/gama-platform/gama/files/9909352/TestConsole.zip)

**To Reproduce**
1. Launch the model 
2. Relaunch the model (with the button from the simulation perspective).
3. Often the previous issue occurs.

Note that, when I relaunch the model several times after the error, it sometimes appears in a wrong order in the messages displayed in the console. (Note that the experiment creates an addition simulation).

The correct display (at first launch) is:
```
(('Init: ' + seed) + ' -- ') + rnd10 -: 'Init: 5.5 -- 0.367428976656514'
(('2. ' + seed) + ' -- ') + rnd10 -: '2. 5.5 -- 0.7173120438790498'
(('Init: ' + seed) + ' -- ') + rnd10 -: 'Init: 5.5 -- 0.367428976656514'
(('2. ' + seed) + ' -- ') + rnd10 -: '2. 5.5 -- 0.7173120438790498' 
```
When relaunching it, I get:
```
(('2. ' + seed) + ' -- ') + rnd10 -: '2. 5.5 -- 0.7173120438790498'
(('Init: ' + seed) + ' -- ') + rnd10 -: 'Init: 5.5 -- 0.367428976656514'
(('2. ' + seed) + ' -- ') + rnd10 -: '2. 5.5 -- 0.7173120438790498'
(('Init: ' + seed) + ' -- ') + rnd10 -: 'Init: 5.5 -- 0.367428976656514'
```
(Init lines is called before the line starting with 2. 
Note also that the colors of the lines do not correspond to the ones of the simulation)...

**Comment by AlexisDrogoul** [comment]
Ive pushed a commit which should fix the issue. Please test !
