### ISSUE TITLE
Gama fails to start on MacOS Ventura with an "old" workspace

### ISSUE THREAD

**Issue by erralb** [gama-platform/gama.old#3534]
### Steps to reproduce
1. update MacOS Ventura 13.0.1

2. start Gama -> crash

3. Tried with and without JDK versions, RC and Alpha versions

### System and version 
Error log : 
```
!SESSION 2022-11-14 11:36:17.644 -----------------------------------------------
eclipse.buildId=${build.id}
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_FR
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -data @noDefault

!ENTRY org.apache.felix.scr 4 0 2022-11-14 11:36:18.371
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.apache.felix.scr [2]
  Unresolved requirement: Import-Package: org.apache.felix.service.command; version="[1.0.0,2.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: org.osgi.service.cm; version="[1.6.0,2.0.0)"; resolution:="optional"
  Unresolved requirement: Import-Package: org.osgi.service.component; version="[1.4.0,1.5.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1783)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:269)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:193)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:139)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:338)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.eclipse.osgi 4 0 2022-11-14 11:36:28.864
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.AssertionFailedException: null argument:The dialog should be created in UI thread
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.jface.dialogs.IconAndMessageDialog.getSWTImage(IconAndMessageDialog.java:288)
	at org.eclipse.jface.dialogs.IconAndMessageDialog.getQuestionImage(IconAndMessageDialog.java:266)
	at org.eclipse.jface.dialogs.MessageDialog.init(MessageDialog.java:249)
	at org.eclipse.jface.dialogs.MessageDialog.<init>(MessageDialog.java:228)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:391)
	at org.eclipse.jface.dialogs.MessageDialog.openQuestion(MessageDialog.java:504)
	at msi.gama.application.Application.checkWorkspace(Application.java:214)
	at msi.gama.application.Application.start(Application.java:144)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

**Comment by hqnghi88** [comment]
Could you please try to delete the old gama workspace in finder and relaunch your gama?

**Comment by AlexisDrogoul** [comment]
I confirm I have the bug on 10.13.0 as well, not with the Git version, only with the downloaded alpha version. However, launching GAMA a second time after renaming the workspace allows to proceed in my case.

**Comment by erralb** [comment]
Thanks for the replies, renaming or deleting the old workspace solves it, thanks !

**Comment by AlexisDrogoul** [comment]
I'm looking into the possibility to create the `Display` before checking the workspace sanity, etc. Not completely sure it is possible with the current architecture, but it would allow to run all dialogs openings, etc. in the correct thread (although I'm sure the problem is not here but in the fact that reading the metadata of eclipse plugins in the old workspace creates the bug).

**Comment by AlexisDrogoul** [comment]
I reopen the issue as it is not "solved" per se 😉 . We still need to understand why we have this issue. @hqnghi88 and I will investigate. In any case, thanks for reporting it.

**Comment by AlexisDrogoul** [comment]
I think it is probably related to #3489 -- permissions changes in macOS + metadata changes in Eclipse plugins. Hopefully we can workaround these !

**Comment by hqnghi88** [comment]
It seems that the workaround is good. I dont have the crash with old workspace on  13.1 beta 2 (with local build)
