### ISSUE TITLE
No GUI when building GAMA with Maven with Eclipse above 2022-03

### ISSUE THREAD

**Issue by RoiArthurB** [gama-platform/gama.old#3540]
**Describe the bug**
When building GAMA with Maven using Eclipse 2022-09 or 2022-12, no graphical interface fills the IDE in old and new workspace even with all lib loaded

![Screenshot from 2022-11-30 11-36-29](https://user-images.githubusercontent.com/16764085/204708859-cd30a739-6b9b-4140-a41d-d49f32fc2f17.png)

![Screenshot from 2022-11-30 11-36-07](https://user-images.githubusercontent.com/16764085/204708872-b7689197-08a3-44f2-8f34-675a37951727.png)

Here's some launched log (displayed after trying to create a new file)

```log
> FLAG: enable_debug                          set to________ true
> FLAG: enable_logging                        set to________ true
> FLAG: use_global_preference_store           set to________ true
> FLAG: read_only                             set to________ false
> FLAG: use_old_tabs                          set to________ true
> FLAG: use_legacy_drawers                    set to________ false
> FLAG: use_delayed_resize                    set to________ false
> FLAG: use_native_opengl_window              set to________ true
> GAMA: version 1.8.2                         loading on____ linux 6.0.10-arch2-1, x86_64, JDK 17.0.5
> JAI : ImageIO extensions                    loaded for____ |jpg|tiff|bmp|gif|arx|tf8|TF8|png|ppm|jp2|tif|TIF|asc|TIFF|btf|BTF|pgm|wbmp|jpeg|pbm
> GAMA: msi.gama.core                         loaded in_____ 1265ms
> GAMA: simtools.gaml.extensions.physics      loaded in_____ 13ms
> GAMA: ummisco.gama.network                  loaded in_____ 7ms
> GAMA: ummisco.gaml.extensions.maths         loaded in_____ 76ms
> GAMA: ummisco.gama.opengl                   loaded in_____ 5ms
> GAMA: ummisco.gama.serialize                loaded in_____ 9ms
> GAMA: simtools.gaml.extensions.traffic      loaded in_____ 42ms
> GAMA: ummisco.gama.java2d                   loaded in_____ 1ms
> GAMA: msi.gaml.architecture.simplebdi       loaded in_____ 63ms
> GAMA: miat.gaml.extension.pedestrian        loaded in_____ 17ms
> GAMA: msi.gaml.extensions.fipa              loaded in_____ 11ms
> GAMA: espacedev.gaml.extensions.genstar     loaded in_____ 13ms
> GAMA: irit.gaml.extensions.database         loaded in_____ 11ms
> GAMA: ummisco.gaml.extensions.stats         loaded in_____ 17ms
> GAMA: all plugins                           loaded in_____ 1683ms
> GAMA: models library                        modified______ Nov 30,2022 11:28:09
> GAMA: OpenGL                                loaded in_____ 432ms
Application started in : 8730ms
> GAMA: models library                        modified______ Nov 30,2022 11:28:09
> GAMA: workspace metadata                    loaded in_____ 21ms
> GAMA: workspace projects                    built in______ 613ms
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:443)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1034)
	at ummisco.gama.ui.wizards.AbstractNewModelWizard.performFinish(AbstractNewModelWizard.java:173)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:833)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:473)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5796)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:304)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5796)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at msi.gama.application.Application.start(Application.java:149)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.NullPointerException: Cannot invoke "ummisco.gama.ui.navigator.contents.ResourceManager.reveal(Object)" because the return value of "ummisco.gama.ui.navigator.contents.ResourceManager.getInstance()" is null
	at ummisco.gama.ui.wizards.AbstractNewModelWizard.doFinish(AbstractNewModelWizard.java:216)
	at ummisco.gama.ui.wizards.AbstractNewModelWizard.lambda$0(AbstractNewModelWizard.java:164)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:434)
	... 59 more
```

![Screenshot from 2022-11-30 11-40-23](https://user-images.githubusercontent.com/16764085/204709036-d99e58a0-7769-48e4-b1c5-fd567bb23398.png)

**Desktop (please complete the following information):**
 - OS: Linux / MacOS M1 air
 - GAMA version: git
 - Java version: 17 LTS (system)
 - Graphics cards / Display system: Intel Chipset

**Additional context**
Maybe this problem comes from some SWT fixes that we introduced in GAMA some time ago.

Also, this problem doesn't happen when launching GAMA from Eclipse as in screenshot below

![Screenshot from 2022-11-30 11-46-03](https://user-images.githubusercontent.com/16764085/204709782-19f96003-7edc-492e-b956-628067466a52.png)

**Comment by AlexisDrogoul** [comment]
Can you compile a version with 2022-12 and post it somewhere ? Seems that the navigator is not loaded (and does not create the resourceManager), which might indicate other errors upstream in SWT...

**Comment by RoiArthurB** [comment]
Hi, here's a fresh built on the latest commit. Only modifications are : Eclipse bumped from 2022-03 to 2022-12 (allowing snapshot version) and removed [2 libraries](https://github.com/gama-platform/gama/blob/GAMA_1.8.2/ummisco.gama.feature.dependencies/feature.xml#L894-L906) creating some compilation troubles
-> https://e1.pcloud.link/publink/show?code=kZ8yLYZ1jjdhDVeRYVPWvd4U4I5Y81IsXoy

**Comment by RoiArthurB** [comment]
Quick update, I updated my Eclipse IDE on the 2022-12 RC2 and I have GAMA running well (just needed to manually install packages xtext, xsd and some apache commons as it's a pre-release not pre-packages as official ones). 

This should confirm that this issue seems more related to Maven than Eclipse.

However, there's an issue while starting experiments about SWTAccessor. It appears only while starting experiment (not while opening files, changing window size, etc) regardless of what it should display (opengl or java2D only have the same issue)


![Screenshot from 2022-12-02 10-00-41](https://user-images.githubusercontent.com/16764085/205205597-d3a180c8-cd8e-4a37-811d-de3c4fb77667.png)

**Comment by RoiArthurB** [comment]
New update : I don't know how it is linked to SWT, but workspace is very badly generated (see link, it's the difference between GAMA 1.8.2-RC2 and git maven built linked above). We can see that GAMA have every possibilities to write in the freshly created workspace, but doesn't init anything inside... 

https://www.diffchecker.com/U7Br6duN

My current hypothese would be that the interface is frozen because of this init failure and would explain why GAMA interface shows up on pre-existing workspace (no need to init it and it can just load those data), but not in new workspace... 🤔🤔🤔

**Comment by AlexisDrogoul** [comment]
The fact that the workspace is not initialised correctly is troubling. This is why a permission problem seems likely, no ?

**Comment by AlexisDrogoul** [comment]
On second thought, looking more closely at the differences, I do not see anything really shocking. Most of the absent data is produced when using the workspace (opening folders, etc.) or using GAMA (dialogs, etc.). So a newly created workspace is not supposed to contain lots of these metadata. Have you compared with the workspace generated from GAMA launched from Eclipse ?

**Comment by RoiArthurB** [comment]
It's definitely different, the version from Eclipse create way more stuff (and the building time once GAMA is started is also longer)...

https://www.diffchecker.com/gvC6C5en

**Comment by AlexisDrogoul** [comment]
@RoiArthurB this issue is normally closed, but you might want to open a new one for the issues in OpenGL under Linux...
