### ISSUE TITLE
At_distance function return incorrect value while using parallel option

### ISSUE THREAD

**Issue by curiosity29** [gama-platform/gama.old#3576]
**Describe the bug**
Try to print out the number of agents at a distance of 200 (which is every agent since the map is 100x100) and this value is different from the total number of agents.
![test050102](https://user-images.githubusercontent.com/62107278/210740210-55ddbcfd-584d-4190-9459-abc28fcfb03b.png)

**To Reproduce**
Using the model:
[test2.txt](https://github.com/gama-platform/gama/files/10350673/test2.txt)

**Expected behavior**
It should be the same as when removing the parallel option.
![test050103](https://user-images.githubusercontent.com/62107278/210740301-2855c6d9-8bda-4168-b8f4-62e10ce5755f.png)

**GAMA version 1.9.0**

**Additional context**
I tried switching the "make species schedule their agents in parallel" in help/preference/execution, it just overwrites my option of using parallel or not.
Also, not directly in this model but sometimes I run into an error of accessing nil agents when using the at_distance function with parallel.

**Comment by lesquoyb** [comment]
While investigating that bug I found that it was actually the same problem as #3572 
With my slightly modified MersenneTwisterRNG.java I get that stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: Index 624 out of bounds for length 624
	at msi.gama.util.random.MersenneTwisterRNG.next(MersenneTwisterRNG.java:220)
	at java.base/java.util.Random.nextDouble(Random.java:463)
	at msi.gama.common.util.RandomUtils.next(RandomUtils.java:500)
	at msi.gama.common.util.RandomUtils.between(RandomUtils.java:444)
	at msi.gama.common.util.RandomUtils.shuffleInPlace(RandomUtils.java:344)
	at msi.gama.common.util.RandomUtils.shuffleInPlace(RandomUtils.java:330)
	at msi.gama.util.ICollector.shuffleInPlaceWith(ICollector.java:47)
	at msi.gama.metamodel.topology.CompoundSpatialIndex.allAtDistance(CompoundSpatialIndex.java:202)
	at msi.gama.metamodel.topology.AbstractTopology.getNeighborsOf(AbstractTopology.java:543)
	at msi.gaml.operators.Spatial$Queries._neighbors(Spatial.java:6911)
	at msi.gaml.operators.Spatial$Queries._neighbors(Spatial.java:6889)
	at msi.gaml.operators.Spatial$Queries.at_distance(Spatial.java:6065)
	at gaml.additions.core.GamlAdditions.lambda$844(GamlAdditions.java:904)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:93)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:103)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:91)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.variables.Variable.getUpdatedValue(Variable.java:798)
	at msi.gama.metamodel.population.GamaPopulation.updateVariables(GamaPopulation.java:400)
	at msi.gama.runtime.ExecutionScope.update(ExecutionScope.java:798)
	at msi.gama.metamodel.agent.AbstractAgent.preStep(AbstractAgent.java:193)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:569)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.lambda$0(ParallelAgentStepper.java:39)
	at msi.gama.runtime.concurrent.AgentSpliterator.forEachRemaining(AgentSpliterator.java:77)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:37)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:1)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:140)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:144)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:144)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:144)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:144)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:144)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:144)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.lang.ArrayIndexOutOfBoundsException: Index 625 out of bounds for length 624
	at msi.gama.util.random.MersenneTwisterRNG.next(MersenneTwisterRNG.java:220)
	at java.base/java.util.Random.nextDouble(Random.java:463)
	at msi.gama.common.util.RandomUtils.next(RandomUtils.java:500)
	at msi.gama.common.util.RandomUtils.between(RandomUtils.java:444)
	at msi.gama.common.util.RandomUtils.shuffleInPlace(RandomUtils.java:344)
	at msi.gama.common.util.RandomUtils.shuffleInPlace(RandomUtils.java:330)
	at msi.gama.util.ICollector.shuffleInPlaceWith(ICollector.java:47)
	at msi.gama.metamodel.topology.GamaQuadTree.findIntersects(GamaQuadTree.java:143)
	at msi.gama.metamodel.topology.GamaQuadTree.allAtDistance(GamaQuadTree.java:156)
	at msi.gama.metamodel.topology.CompoundSpatialIndex.allAtDistance(CompoundSpatialIndex.java:200)
	at msi.gama.metamodel.topology.AbstractTopology.getNeighborsOf(AbstractTopology.java:543)
	at msi.gaml.operators.Spatial$Queries._neighbors(Spatial.java:6911)
	at msi.gaml.operators.Spatial$Queries._neighbors(Spatial.java:6889)
	at msi.gaml.operators.Spatial$Queries.at_distance(Spatial.java:6065)
	at gaml.additions.core.GamlAdditions.lambda$844(GamlAdditions.java:904)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:93)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:103)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:91)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.variables.Variable.getUpdatedValue(Variable.java:798)
	at msi.gama.metamodel.population.GamaPopulation.updateVariables(GamaPopulation.java:400)
	at msi.gama.runtime.ExecutionScope.update(ExecutionScope.java:798)
	at msi.gama.metamodel.agent.AbstractAgent.preStep(AbstractAgent.java:193)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:569)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.lambda$0(ParallelAgentStepper.java:39)
	at msi.gama.runtime.concurrent.AgentSpliterator.forEachRemaining(AgentSpliterator.java:77)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:37)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:1)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:140)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:144)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
java.lang.ArrayIndexOutOfBoundsException: Index 624 out of bounds for length 624
	at msi.gama.util.random.MersenneTwisterRNG.next(MersenneTwisterRNG.java:220)
	at java.base/java.util.Random.nextDouble(Random.java:463)
	at msi.gama.common.util.RandomUtils.next(RandomUtils.java:500)
	at msi.gama.common.util.RandomUtils.between(RandomUtils.java:444)
	at msi.gama.common.util.RandomUtils.shuffleInPlace(RandomUtils.java:344)
	at msi.gama.common.util.RandomUtils.shuffleInPlace(RandomUtils.java:330)
	at msi.gama.util.ICollector.shuffleInPlaceWith(ICollector.java:47)
	at msi.gama.metamodel.topology.GamaQuadTree.findIntersects(GamaQuadTree.java:143)
	at msi.gama.metamodel.topology.GamaQuadTree.allAtDistance(GamaQuadTree.java:156)
	at msi.gama.metamodel.topology.CompoundSpatialIndex.allAtDistance(CompoundSpatialIndex.java:200)
	at msi.gama.metamodel.topology.AbstractTopology.getNeighborsOf(AbstractTopology.java:543)
	at msi.gaml.operators.Spatial$Queries._neighbors(Spatial.java:6911)
	at msi.gaml.operators.Spatial$Queries._neighbors(Spatial.java:6889)
	at msi.gaml.operators.Spatial$Queries.at_distance(Spatial.java:6065)
	at gaml.additions.core.GamlAdditions.lambda$844(GamlAdditions.java:904)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:93)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:103)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:91)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.variables.Variable.getUpdatedValue(Variable.java:798)
	at msi.gama.metamodel.population.GamaPopulation.updateVariables(GamaPopulation.java:400)
	at msi.gama.runtime.ExecutionScope.update(ExecutionScope.java:798)
	at msi.gama.metamodel.agent.AbstractAgent.preStep(AbstractAgent.java:193)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:569)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.lambda$0(ParallelAgentStepper.java:39)
	at msi.gama.runtime.concurrent.AgentSpliterator.forEachRemaining(AgentSpliterator.java:77)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:37)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:1)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:140)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:144)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:144)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Adding exception 1 occurence in fish984 at cycle 0: Java error: index out of bounds
in Simulation 0
in int friends update: length(fish at_distance 200.0) + 1 ;
ArrayIndexOutOfBoundsException: Index 624 out of bounds for length 624
msi.gama.util.random.MersenneTwisterRNG.next(MersenneTwisterRNG.java:220)
java.base/java.util.Random.nextDouble(Random.java:463)
msi.gama.common.util.RandomUtils.next(RandomUtils.java:500)
msi.gama.common.util.RandomUtils.between(RandomUtils.java:444)
msi.gama.common.util.RandomUtils.shuffleInPlace(RandomUtils.java:344)
msi.gama.common.util.RandomUtils.shuffleInPlace(RandomUtils.java:330)
msi.gama.util.ICollector.shuffleInPlaceWith(ICollector.java:47)
when applying the at_distance operator on fish and 200.0
in agent fish984
```

**Comment by AlexisDrogoul** [comment]
Not exactly sure about what's happening here, but the reason of this difference is that some agents, when `parallel:` is set to `true`, are removed from the population, but kept in the spatial quad tree that holds all the agents and supports the computation of spatial queries like `at_distance`. I will investigate more.

**Comment by AlexisDrogoul** [comment]
I have committed a version where you can obtain an explicitly synchronised version of the spatial index by setting a preference (see Preferences > Experimental).

Or you can also set it in your experiment:

```gaml
experiment main
{
	init {
		gama.pref_synchronize_quadtree <- true;
	}

      // other stuff

}
```

This will remove some errors (not all, unfortunately). Note however that using `parallel` will create errors when gathering agents, etc. And you might want to simplify a lot of things to avoid problems. 

For instance, instead of having a `fish_killer`, simply prefer letting the simulation do the job. Or do not ask `one_of(fish)` to tell you the number of fish around and/or the size of the population: simply let the simulation, again, do it, as it is implicitly synchronised with the sub-populations (in a global reflex, for instance).
