### ISSUE TITLE
Step facet of parameter doesn't work with an expression

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3581]
**Describe the bug**
If using an expression for the value of a parameter, the experiment won't run (clicking on the run button works but nothing happens)
Example:
```


global {
	
	float dummy;
	init {
		write dummy;
	}
	
}

experiment bug type:batch until:cycle > 0{
	
	parameter "Dummy" var:dummy step:1*3 min:0 max:150;
}
```
It can be annoying because it forbids the use of constants like `#day`, `#minute` etc to define complex steps

**Comment by curiosity29** [comment]
Not sure if it's the same bug but I think with a batch like this:
```
model NewModel
global
{
	int a <-0;
	int b<-0;
}

experiment batch type: batch until: cycle > 0
{
	parameter "a " var: a min: 1 max: 2 step: 1;
	parameter "b " var: b min: a max: 2 step: 1;
	reflex 
	{
			write b;
	}
}
```

the value of variable a in the parameter b's range should be updated because there should be an order to those parameters.

current result:
0
1
2
0
1
2

expected:
1
2
2

**Comment by AlexisDrogoul** [comment]
Why has this issue been reopened ?

**Comment by lesquoyb** [comment]
Because it was closed by mistake, it is not fixed yet

**Comment by AlexisDrogoul** [comment]
The problem comes from the recent fix regarding the `min`, `max` and `step` facets, which assumes that `step` will be a `float` constant. This fix was introduced in https://github.com/gama-platform/gama/commit/bac230b6649932e0454c57aa2f5a745949f20eba . 
I have reworked it a bit, trying to fix this issue.

**Comment by lesquoyb** [comment]
It is still  not working, when trying to run the example model nothing happens and that error stack is printed in eclipse:
```
!MESSAGE org.eclipse.xtext.builder.clustering.ClusteringBuilderState  - Error validating platform:/resource/test%20de%20trucs/models/New%20Model1.gaml

!STACK 0
java.lang.NumberFormatException: For input string: "*1,3"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:476)
	at msi.gaml.variables.Variable$VarValidator.assertCanBeParameter(Variable.java:411)
	at msi.gaml.variables.Variable$VarValidator.validate(Variable.java:266)
	at msi.gaml.compilation.IDescriptionValidator.validate(IDescriptionValidator.java:63)
	at msi.gaml.descriptions.SymbolDescription.validate(SymbolDescription.java:739)
	at msi.gaml.descriptions.IDescription.lambda$2(IDescription.java:176)
	at msi.gama.util.IMap.forEachValue(IMap.java:635)
	at msi.gaml.descriptions.ExperimentDescription.visitOwnChildren(ExperimentDescription.java:231)
	at msi.gaml.descriptions.SymbolDescription.validateChildren(SymbolDescription.java:987)
	at msi.gaml.descriptions.SpeciesDescription.validateChildren(SpeciesDescription.java:915)
	at msi.gaml.descriptions.SymbolDescription.validate(SymbolDescription.java:733)
	at msi.gaml.descriptions.TypeDescription.validate(TypeDescription.java:845)
	at msi.gaml.descriptions.IDescription.lambda$2(IDescription.java:176)
	at msi.gama.util.IMap.forEachValue(IMap.java:635)
	at msi.gaml.descriptions.ModelDescription.visitOwnChildren(ModelDescription.java:487)
	at msi.gaml.descriptions.SymbolDescription.validateChildren(SymbolDescription.java:987)
	at msi.gaml.descriptions.SpeciesDescription.validateChildren(SpeciesDescription.java:915)
	at msi.gaml.descriptions.SymbolDescription.validate(SymbolDescription.java:733)
	at msi.gaml.descriptions.TypeDescription.validate(TypeDescription.java:845)
	at msi.gaml.descriptions.ModelDescription.validate(ModelDescription.java:534)
	at msi.gama.lang.gaml.resource.GamlResource.validate(GamlResource.java:294)
	at msi.gama.lang.gaml.validation.GamlResourceValidator.validate(GamlResourceValidator.java:62)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.addMarkers(DefaultResourceUIValidatorExtension.java:61)
	at org.eclipse.xtext.ui.validation.DefaultResourceUIValidatorExtension.updateValidationMarkers(DefaultResourceUIValidatorExtension.java:47)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.processDelta(MarkerUpdaterImpl.java:94)
	at org.eclipse.xtext.builder.builderState.MarkerUpdaterImpl.updateMarkers(MarkerUpdaterImpl.java:64)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.updateMarkers(AbstractBuilderState.java:137)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:285)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:171)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:521)
	at org.eclipse.xtext.builder.impl.XtextBuilder.addInfosFromTaskAndBuild(XtextBuilder.java:455)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:436)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:339)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by AlexisDrogoul** [comment]
hmmm... Not possible. The call to this function (`java.lang.Float.parseFloat`) has been removed from the Java code ...

**Comment by lesquoyb** [comment]
Oops seems like eclipse needed a clean. It works great
