### ISSUE TITLE
Random simulation error

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3597]
**Describe the bug**
While testing `Incremental Model 6` a few errors happened:
 - the simulation would pause without any reason (I tried to comment out the "do pause" line but it didn't change anything)
 - at random time the simulation would stop with an error looking like this:
 ```
1 occurence in people335 (dead) at cycle 240: Java error: nil value detected
in Simulation 0
in draw sphere(float(3)) at: point(location.x,location.y,location.z + 3) color: is_infected ? #red : #green ;
NullPointerException: Cannot invoke "msi.gama.metamodel.shape.GamaPoint.getZ()" because "<parameter2>[0]" is null
gaml.additions.core.GamlAdditions.lambda$194(GamlAdditions.java:267)
msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:105)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:91)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
msi.gaml.operators.Points.toPoint(Points.java:112)
gaml.additions.core.GamlAdditions.lambda$791(GamlAdditions.java:851)
when applying the z operator on null
when applying the point operator on [location.x, location.y, +(location.z,3)]
in draw sphere(float(3)) at: point(location.x,location.y,location.z + 3) color: is_infected ? #red : #green ;
in agent people335 (dead)
 ```
and the stack in eclipse console looks like this:
```
java.lang.NullPointerException: Cannot invoke "msi.gama.metamodel.shape.GamaPoint.getX()" because "o[0]" is null
	at gaml.additions.core.GamlAdditions.lambda$192(GamlAdditions.java:265)
	at msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:105)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.operators.Points.toPoint(Points.java:109)
	at gaml.additions.core.GamlAdditions.lambda$788(GamlAdditions.java:848)
	at msi.gaml.expressions.operators.AbstractNAryOperator._value(AbstractNAryOperator.java:350)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.statements.draw.AttributeHolder$ExpressionAttribute.value(AttributeHolder.java:181)
	at msi.gaml.statements.draw.AttributeHolder$ExpressionAttribute.refresh(AttributeHolder.java:194)
	at msi.gaml.statements.draw.AttributeHolder.lambda$0(AttributeHolder.java:282)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at msi.gaml.statements.draw.AttributeHolder.refresh(AttributeHolder.java:282)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:389)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:370)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:225)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:206)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:105)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:73)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:110)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:168)
	at ummisco.gama.opengl.view.SWTOpenGLDisplaySurface.updateDisplay(SWTOpenGLDisplaySurface.java:255)
	at ummisco.gama.ui.views.displays.LayeredDisplayView$2.run(LayeredDisplayView.java:355)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

It's often at the "draw sphere" line when accessing the location, but sometimes also at the 
```
draw shape color: nb_total = 0 ? #gray : (float(nb_infected) / nb_total > 0.5 ? #red : #green) border: #black depth: height;
```
line where there's a division by 0 exception

**To Reproduce**
In my case I can reproduce by running this model, but it doesn't work on other computers so far.

**Additional context**
- I tried with the release version and the git version, tried to relaunch gama, tried to change the random generator (mersenne, java, threaded and parallel) and I tried reboot my computer, but the error still happens.
- It is likely a thread related bug, as the "division by zero" bug suggests (it's inconsistent in the same line of gaml code) as well as the fact that the cycle where the error happens is different from the cycle where the simulation actually stops ![image](https://user-images.githubusercontent.com/6374469/215957356-a77bde9e-8f8d-416f-8b26-8ae64a680436.png)
- Therefore I think it's hard to reproduce because the error is probably silent on most computer, depending on it's state/architecture/os etc

**Comment by hqnghi88** [comment]
I remember that some technical problem in display cannot be solved (maybe it's outdated now) and we have the choice to permanently silent them
<img width="266" alt="image" src="https://user-images.githubusercontent.com/6105384/216066153-794fb6db-e1ac-4668-a6cb-07f353f23815.png">

**Comment by lesquoyb** [comment]
YES ! I had that "show errors thrown in displays and outputs" set to true, setting it to false makes the model run normally. And I was able to reproduce on another computer by setting it to true.
Now I don't know if it's still a bug or not...

**Comment by AlexisDrogoul** [comment]
It is not a bug. There are some GAMA errors that we can't prevent in the UI thread (usually not synchronised with the simulation), and some errors in Java2D and OpenGL rendering that are also unavoidable (like zero sized geometries, etc.). That is why this switch (set initially to false) exists in the preferences.
