### ISSUE TITLE
NullPointerException in example model "Moving Agents"

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3602]
**Describe the bug**
When running the example model `Moving Agents.gaml`, I randomly encounter null pointer exception when releasing captured agents. The message in eclipse:
```
java.lang.NullPointerException: Cannot read field "minx" because "env" is null
	at org.locationtech.jts.geom.Envelope.init(Envelope.java:242)
	at org.locationtech.jts.geom.Envelope.<init>(Envelope.java:166)
	at org.locationtech.jts.geom.Geometry.getEnvelopeInternal(Geometry.java:625)
	at org.locationtech.jts.algorithm.locate.SimplePointInAreaLocator.locate(SimplePointInAreaLocator.java:71)
	at org.locationtech.jts.algorithm.locate.SimplePointInAreaLocator.locate(SimplePointInAreaLocator.java:202)
	at org.locationtech.jts.geom.prep.PreparedPolygonPredicate.isAnyTargetComponentInAreaTest(PreparedPolygonPredicate.java:160)
	at org.locationtech.jts.geom.prep.AbstractPreparedPolygonContains.eval(AbstractPreparedPolygonContains.java:151)
	at org.locationtech.jts.geom.prep.PreparedPolygonCovers.covers(PreparedPolygonCovers.java:64)
	at org.locationtech.jts.geom.prep.PreparedPolygonCovers.covers(PreparedPolygonCovers.java:42)
	at org.locationtech.jts.geom.prep.PreparedPolygon.covers(PreparedPolygon.java:121)
	at msi.gama.metamodel.topology.AbstractTopology.accept(AbstractTopology.java:590)
	at msi.gama.metamodel.topology.AbstractTopology.lambda$1(AbstractTopology.java:613)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at msi.gama.metamodel.topology.AbstractTopology.getAgentsIn(AbstractTopology.java:610)
	at msi.gaml.operators.Spatial$Queries._gather(Spatial.java:6818)
	at msi.gaml.operators.Spatial$Queries.relatedEntities(Spatial.java:6110)
	at msi.gaml.operators.Spatial$Queries.inside(Spatial.java:6147)
	at gaml.additions.core.GamlAdditions.lambda$990(GamlAdditions.java:1050)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:93)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:91)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.statements.LetStatement.privateExecuteIn(LetStatement.java:140)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.statements.AbstractStatementSequenceWithArgs.privateExecuteIn(AbstractStatementSequenceWithArgs.java:59)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.outputs.layers.EventLayer.lambda$0(EventLayer.java:202)
	at msi.gama.runtime.GAMA.runAndUpdateAll(GAMA.java:514)
	at msi.gama.outputs.layers.EventLayer.executeEvent(EventLayer.java:202)
	at msi.gama.outputs.layers.EventLayer.mouseMove(EventLayer.java:163)
	at ummisco.gama.opengl.view.SWTOpenGLDisplaySurface.dispatchMouseEvent(SWTOpenGLDisplaySurface.java:746)
	at ummisco.gama.ui.views.displays.LayeredDisplayMultiListener.mouseMove(LayeredDisplayMultiListener.java:198)
	at ummisco.gama.opengl.view.NEWTLayeredDisplayMultiListener.mouseMoved(NEWTLayeredDisplayMultiListener.java:136)
	at jogamp.newt.WindowImpl.dispatchMouseEvent(WindowImpl.java:4215)
	at jogamp.newt.WindowImpl.consumePointerEvent(WindowImpl.java:4063)
	at jogamp.newt.WindowImpl.consumeEvent(WindowImpl.java:3461)
	at jogamp.newt.WindowImpl.doEvent(WindowImpl.java:3403)
	at jogamp.newt.WindowImpl.doPointerEvent(WindowImpl.java:3848)
	at jogamp.newt.WindowImpl.doMouseEvent(WindowImpl.java:3511)
	at jogamp.newt.WindowImpl.sendMouseEvent(WindowImpl.java:3478)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at msi.gama.application.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Adding exception 1 occurence in Simulation 0 at cycle 36049: Java error: nil value detected
in Simulation 0
in list<being> other_agents <- (being inside at_location(zone,#user_location)) - moved_agents;
NullPointerException: Cannot read field "minx" because "env" is null
org.locationtech.jts.geom.Envelope.init(Envelope.java:242)
org.locationtech.jts.geom.Envelope.<init>(Envelope.java:166)
org.locationtech.jts.geom.Geometry.getEnvelopeInternal(Geometry.java:625)
org.locationtech.jts.algorithm.locate.SimplePointInAreaLocator.locate(SimplePointInAreaLocator.java:71)
org.locationtech.jts.algorithm.locate.SimplePointInAreaLocator.locate(SimplePointInAreaLocator.java:202)
org.locationtech.jts.geom.prep.PreparedPolygonPredicate.isAnyTargetComponentInAreaTest(PreparedPolygonPredicate.java:160)
org.locationtech.jts.geom.prep.AbstractPreparedPolygonContains.eval(AbstractPreparedPolygonContains.java:151)
when applying the inside operator on being and polygon ([{753.7661132812501,518.785034179687,0.0},{751.8446413215732,499.27600197807476,0.0},{746.1540665323788,480.5166909431782,0.0},{736.913074511505,463.228010877727,0.0},{724.476791399905,448.0743560610325,0.0},{709.3231365832106,435.63807294943274,0.0},{692.0344565177598,426.3970809285587,0.0},{673.2751454828632,420.70650613936425,0.0},{653.7661132812499,418.7850341796874,0.0},{634.2570810796373,420.70650613936425,0.0},{615.4977700447413,426.3970809285587,0.0},{598.2090899792896,435.63807294943274,0.0},{583.0554351625955,448.0743560610325,0.0},{570.6191520509957,463.228010877727,0.0},{561.3781600301212,480.5166909431782,0.0},{555.6875852409272,499.27600197807476,0.0},{553.7661132812501,518.785034179687,0.0},{555.6875852409272,538.2940663813007,0.0},{561.3781600301212,557.0533774161964,0.0},{570.6191520509957,574.3420574816477,0.0},{583.0554351625955,589.495712298342,0.0},{598.2090899792896,601.931995409942,0.0},{615.4977700447411,611.1729874308163,0.0},{634.257081079637,616.8635622200105,0.0},{653.7661132812499,618.7850341796876,0.0},{673.2751454828632,616.8635622200105,0.0},{692.0344565177598,611.1729874308163,0.0},{709.3231365832106,601.931995409942,0.0},{724.476791399905,589.495712298342,0.0},{736.913074511505,574.3420574816477,0.0},{746.1540665323788,557.0533774161967,0.0},{751.8446413215732,538.2940663813007,0.0},{753.7661132812501,518.785034179687,0.0}])
in list<being> other_agents <- (being inside at_location(zone,#user_location)) - moved_agents;
in agent Simulation 0
```
**Note**: I have to capture and release many times before the bug occurs

**Comment by lesquoyb** [comment]
Reopening because now there are a lot of errors in the eclipse console:
```
Error when drawing in a display : Points of LinearRing do not form a closed linestring
java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring
	at org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:91)
	at org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:86)
	at org.locationtech.jts.geom.LinearRing.copyInternal(LinearRing.java:133)
	at org.locationtech.jts.geom.LinearRing.copyInternal(LinearRing.java:32)
	at org.locationtech.jts.geom.Geometry.copy(Geometry.java:1606)
	at org.locationtech.jts.geom.Polygon.copyInternal(Polygon.java:347)
	at org.locationtech.jts.geom.Polygon.copyInternal(Polygon.java:46)
	at org.locationtech.jts.geom.Geometry.copy(Geometry.java:1606)
	at msi.gaml.statements.draw.ShapeExecuter.executeOn(ShapeExecuter.java:123)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:403)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:374)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:225)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:206)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:105)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:73)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:110)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:168)
	at ummisco.gama.java2d.Java2DDisplaySurface.paintComponent(Java2DDisplaySurface.java:492)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5311)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1657)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1632)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5259)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5069)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:879)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
Nothing happens for the enduser though

**Comment by AlexisDrogoul** [comment]
I move this to @ptaillandier  -- I do not really understand why we keep on having these errors when copying even super simple geometries.

**Comment by hqnghi88** [comment]
To recall , it is the Same error message in #3433
