### ISSUE TITLE
closest_to returns nil when it shouldn't

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3626]
**Describe the bug**
There are some cases where the operator `closest_to` returns `nil` while given a non empty list of agents and a valid location.

**To Reproduce**
1. Run the model `Mas KMeans Interactive.gaml`
2. place a few points and groups
3. Then try to erase a point
4. The simulation stops without any message
5. If you try to erase a point again, an error appear:
```
1 occurence in Simulation 0 at cycle 280685: Can not execute ask on a nil agent
in Simulation 0
in ask closest_to(close_ag,#user_location)  {
	if self is 'datapoints'  {
		centroids c <- datapoints(self).mycenter;
		if c != nil  {
			c.mypoints >- self;
		}
	
	}else  {
		ask centroids(self).mypoints  {
			mycenter <- nil;
			color_kmeans <- rgb(225,225,225);
		}
	
	}
	

	do die ;
}

in ask closest_to(close_ag,#user_location)  {
	if self is 'datapoints'  {
		centroids c <- datapoints(self).mycenter;
		if c != nil  {
			c.mypoints >- self;
		}
	
	}else  {
		ask centroids(self).mypoints  {
			mycenter <- nil;
			color_kmeans <- rgb(225,225,225);
		}
	
	}
	

	do die ;
}

in agent Simulation 0
```
The problem is the `close_ag` list is not empty and the `#user_location` is a normal point. I added some write statements just before the `ask` to be sure and everything seems normal.

**Expected behavior**
the closest point disappear and the simulation do not crash

**Additional context**
I tried to run the model from the git version to get more information, but I encounter another problem: whenever I try to create the first group, the model crashes with a NPE:
```

java.lang.NullPointerException: Cannot invoke "msi.gama.util.IContainer.isEmpty(msi.gama.runtime.IScope)" because "o[0]" is null
	at gaml.additions.core.GamlAdditions.lambda$334(GamlAdditions.java:391)
	at msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:106)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:104)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.operators.Containers.where(Containers.java:2257)
	at msi.gaml.operators.Containers.where(Containers.java:2293)
	at gaml.additions.core.GamlAdditions.lambda$473(GamlAdditions.java:530)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:99)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.statements.AskStatement.privateExecuteIn(AskStatement.java:221)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:90)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:112)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:206)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:242)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:536)
	at msi.gama.common.interfaces.IScopedStepable.step(IScopedStepable.java:27)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Adding exception 1 occurence in Simulation 0 at cycle 74371: Java error: nil value detected
in Simulation 0
in ask centroids where not(empty(each.mypoints))  {
	location <- mean(mypoints collect each.location);
	float oldist <- myIntraDistance;
	myIntraDistance <- sum_of(mypoints,distance_to(each,self));
	converged <- with_precision(oldist - myIntraDistance,2) = 0;
}
```

**Comment by AlexisDrogoul** [comment]
A very simple way to reproduce the bug : 

```gaml

model ClosestToBug


global {
	
	init {
		create a;
		create b;
		list<agent> c <- list(a+b);
		write (a+b )closest_to self;
		write c closest_to self;
	}
}

species a;
species b;

experiment run;
```

The first `write` return either `a(0)` or `b(0)` (as both are inside the world), but the second systematically `nil`.

As can be seen, the only difference between the two is that the second expression uses a `list<agent>` for the left member.

**Comment by AlexisDrogoul** [comment]
I just committed a very simple fix, thank you for testing it.

**Comment by lesquoyb** [comment]
The issue is solved in your example model, but when I try to run the `MAS KMean Interactive` model I now have a NPE when I create a group. Here in gama:
```
1 occurence in Simulation 0 at cycle 82575: Java error: nil value detected
in Simulation 0
in ask centroids where not(empty(each.mypoints))  {
	location <- mean(mypoints collect each.location);
	float oldist <- myIntraDistance;
	myIntraDistance <- sum_of(mypoints,distance_to(each,self));
	converged <- with_precision(oldist - myIntraDistance,2) = 0;
}

NullPointerException: Cannot invoke "msi.gama.util.IContainer.isEmpty(msi.gama.runtime.IScope)" because "o[0]" is null
gaml.additions.core.GamlAdditions.lambda$333(GamlAdditions.java:390)
msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:106)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:104)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
msi.gaml.operators.Containers.where(Containers.java:2257)
msi.gaml.operators.Containers.where(Containers.java:2293)
when applying the empty operator on null
in ask centroids where not(empty(each.mypoints))  {
	location <- mean(mypoints collect each.location);
	float oldist <- myIntraDistance;
	myIntraDistance <- sum_of(mypoints,distance_to(each,self));
	converged <- with_precision(oldist - myIntraDistance,2) = 0;
}

in agent Simulation 0
```

and in the eclipse console:
```
Caused by: java.lang.NullPointerException: Cannot invoke "msi.gaml.types.IType.getName()" because "t" is null
	at msi.gaml.types.ParametricType.useCacheFor(ParametricType.java:63)
	at msi.gaml.types.ParametricType.createParametricType(ParametricType.java:80)
	at msi.gaml.types.GamaContainerType.of(GamaContainerType.java:103)
	at msi.gama.util.GamaList.<init>(GamaList.java:69)
	at msi.gama.util.GamaListFactory.create(GamaListFactory.java:464)
	at msi.gaml.types.GamaListType.staticCast(GamaListType.java:66)
	at msi.gaml.operators.Cast.asList(Cast.java:503)
	at msi.gaml.statements.LoopStatement$Over.runIn(LoopStatement.java:581)
	at msi.gaml.statements.LoopStatement.privateExecuteIn(LoopStatement.java:436)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:225)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:206)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:105)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:73)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:110)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:168)
	... 30 more
java.lang.NullPointerException: Cannot invoke "msi.gama.util.IContainer.isEmpty(msi.gama.runtime.IScope)" because "o[0]" is null
	at gaml.additions.core.GamlAdditions.lambda$333(GamlAdditions.java:390)
	at msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:106)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:104)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.operators.Containers.where(Containers.java:2257)
	at msi.gaml.operators.Containers.where(Containers.java:2293)
	at gaml.additions.core.GamlAdditions.lambda$467(GamlAdditions.java:524)
	at msi.gaml.expressions.operators.BinaryOperator._value(BinaryOperator.java:99)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
	at msi.gaml.statements.AskStatement.privateExecuteIn(AskStatement.java:221)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:90)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:112)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:206)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:242)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:547)
	at msi.gama.common.interfaces.IScopedStepable.step(IScopedStepable.java:27)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Adding exception 1 occurence in Simulation 0 at cycle 82575: Java error: nil value detected
in Simulation 0
in ask centroids where not(empty(each.mypoints))  {
	location <- mean(mypoints collect each.location);
	float oldist <- myIntraDistance;
	myIntraDistance <- sum_of(mypoints,distance_to(each,self));
	converged <- with_precision(oldist - myIntraDistance,2) = 0;
}

NullPointerException: Cannot invoke "msi.gama.util.IContainer.isEmpty(msi.gama.runtime.IScope)" because "o[0]" is null
gaml.additions.core.GamlAdditions.lambda$333(GamlAdditions.java:390)
msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:106)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
msi.gaml.expressions.operators.UnaryOperator._value(UnaryOperator.java:104)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:81)
msi.gaml.operators.Containers.where(Containers.java:2257)
msi.gaml.operators.Containers.where(Containers.java:2293)
when applying the empty operator on null
in ask centroids where not(empty(each.mypoints))  {
	location <- mean(mypoints collect each.location);
	float oldist <- myIntraDistance;
	myIntraDistance <- sum_of(mypoints,distance_to(each,self));
	converged <- with_precision(oldist - myIntraDistance,2) = 0;
}

in agent Simulation 0
```

**Comment by AlexisDrogoul** [comment]
I do not get any error... What do you mean by "creating a group" ?

**Comment by lesquoyb** [comment]
It doesn't appear every time, and sometimes it just stops but nothing is displayed, so you may have to create a few groups. What I mean by that is clicking on the X symbol then clicking in the display.
I also have a breakpoint in UnaryOperator.java on the catching of an exception at line 113 that is sometimes reached too

**Comment by AlexisDrogoul** [comment]
OK. I think I see more or less what happens. Two issues collide here. 
1. When the population create agents, they are actually added to the list of agents *before* their variables are computed. I have therefore made a trial attempt by inverting the two statements : we compute the variables and then we add the agents to the list. It makes completely sense to proceed like this, but I hope it is not gonna break anything as the creation of agent is a kind of crucial piece of logic... 
2. When adding agents outside the normal schedule (i.e. they are created by the user), the risk is to have concurrent modification exceptions happening (a function is computed over a population, an agent is added in the middle of this computation...). The good solution would be to have an intermediate list in the model (i.e. agents_to_add, with the location of the last mouse click(s)), which would be created asynchronously by the user and then synchronously "transformed" into either centroid or datapoint in a reflex in global. I can also implement a more general solution, that would solve several of these "concurrent modifications" problem, by systematically creating working copies of collections whenever a function is computed on them. However, I am afraid of the cost it might inflict to large models where, for instance, statistical operators are executed over thousands of agents. Copying them over and over seems like a waste of time and resources.

**Comment by lesquoyb** [comment]
I think for the moment we can just add that info somewhere in the documentation and modify a bit our models accordingly.
Apart from the computational cost you mentioned, I'm not a fan a touching anything crucial currently as it may call for other problems and overall bring some instability

**Comment by hqnghi88** [comment]
For the 2, I prefer to have the first proposal: agent-to-add, as in near future ( gamaserver, separating modules) we will soon tackle this issue of synchronizing the UI and simulations. In fact in mmorgp, the agents have status such as preparing (just shown its aspect in the UI, no computation) or ready (take into account of simulation, next step, obviously)
