### ISSUE TITLE
Gama crashes after installing some plugins

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3634]
**Describe the bug**
I tried to install the `GAMR` plugin into a gama release, but since then gama can't open: I have the splash screen and then a dialog saying it crashed and giving the log file location, it happens before selecting workspace. I already noticed that behavior before with the `ImageAnalysis` plugin so I don't think it's related to a specific plugin but more about the installation/loading process.
Here is the log file I get: [1677129621756.log](https://github.com/gama-platform/gama/files/10810525/1677129621756.log)

**To Reproduce**
1. Install the plugin `GAMR` from experimental
2. restart gama
3. See error

**Additional context**
The plugin `camisole` seems to work fine

**Comment by AlexisDrogoul** [comment]
Could you check if `org.eclipse.equinox.common` is present in the application and in which version ? A lot of the errors seem to revolve around it missing somehow...

**Comment by lesquoyb** [comment]
I do have `org.eclipse.equinox.common_3.17.0.v20221108-1156.jar` in my installation `plugins` folder

**Comment by lesquoyb** [comment]
As a side note, there's a workaround to get back to a configuration without plugins by removing the content of the `.eclipse` folder,  I documented it [here](https://gama-platform.org/wiki/next/Troubleshooting#installation-is-broken)

**Comment by lesquoyb** [comment]
Update: with the very latest release, `GAMR` can be installed without any problems (though I have no idea what it's supposed to bring, but that's another issue), but `mike and hecras` as well as `Qrcode` and `ImageAnalysis` can be installed, but then it is impossible to refresh the workspace in GAMA or to open a model anymore:
![image](https://user-images.githubusercontent.com/6374469/221144582-d5798267-c960-4e3b-866e-04f7f23ba429.png)
here is what happen when trying to open an editor view (see also that the refreshing action is stuck to 0%)

**Comment by AlexisDrogoul** [comment]
Hi,

Do you somewhere a log of what's happening in the last case (with the whole stack of messages) ? I would be interested in implementing a workaround that would consist in opening the GAML file in a text editor when the GAML editor can't be opened (and also in understanding why it can't be opened)

**Comment by lesquoyb** [comment]
here is the whole stack:
```
org.eclipse.core.runtime.CoreException: Failed to create injector for msi.gama.lang.gaml.Gaml (occurred in msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory)
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.handleCreationError(AbstractGuiceAwareExecutableExtensionFactory.java:97)
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:65)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:265)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:281)
	at org.eclipse.ui.internal.registry.EditorDescriptor.createEditor(EditorDescriptor.java:231)
	at org.eclipse.ui.internal.EditorReference.createPart(EditorReference.java:321)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPart(CompatibilityPart.java:304)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPart(CompatibilityEditor.java:61)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:342)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:995)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:960)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:140)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:403)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:330)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1208)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:116)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:677)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:544)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:528)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:73)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:995)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:659)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveRenderer.processContents(PerspectiveRenderer.java:51)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.showTab(PerspectiveStackRenderer.java:82)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:116)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.postProcess(PerspectiveStackRenderer.java:64)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:677)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:150)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:72)
	at org.eclipse.e4.ui.workbench.renderers.swt.WBWRenderer.processContents(WBWRenderer.java:658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:673)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:763)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:728)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:712)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1083)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at msi.gama.application.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.RuntimeException: Failed to create injector for msi.gama.lang.gaml.Gaml
	at ummisco.gama.ui.modeling.internal.ModelingActivator.createInjector(ModelingActivator.java:108)
	at ummisco.gama.ui.modeling.internal.ModelingActivator.getInjector(ModelingActivator.java:86)
	at msi.gama.lang.gaml.ui.GamlExecutableExtensionFactory.getInjector(GamlExecutableExtensionFactory.java:26)
	at org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory.create(AbstractGuiceAwareExecutableExtensionFactory.java:54)
	... 112 more
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NullPointerException: Cannot invoke "msi.gaml.descriptions.ModelDescription.getAllSpecies(java.util.List)" because "<local0>" is null
  at BuiltinGlobalScopeProvider.<init>(BuiltinGlobalScopeProvider.java:165)
  at BuiltinGlobalScopeProvider.class(BuiltinGlobalScopeProvider.java:147)
  while locating BuiltinGlobalScopeProvider
  at MethodBasedModule.configure(MethodBasedModule.java:58)
      \_ installed by: Modules$OverrideModule -> Modules$OverrideModule -> GamlRuntimeModule
  at CrossReferenceTemplateVariableResolver.globalScopeProvider(CrossReferenceTemplateVariableResolver.java:39)
      \_ for field globalScopeProvider
  at CrossReferenceTemplateVariableResolver.class(CrossReferenceTemplateVariableResolver.java:39)
  at XtextTemplateContextType.setCrossReferenceResolver(XtextTemplateContextType.java:31)
      \_ for 1st parameter resolver
  while locating XtextTemplateContextType
  at XtextTemplateContextTypeRegistry.<init>(XtextTemplateContextTypeRegistry.java:38)
  at XtextTemplateContextTypeRegistry.class(XtextTemplateContextTypeRegistry.java:38)
  while locating XtextTemplateContextTypeRegistry
  at LanguageRegistrar.contextTypeRegistry(LanguageRegistrar.java:24)
      \_ for field contextTypeRegistry
  at MethodBasedModule.configure(MethodBasedModule.java:58)
      \_ installed by: Modules$OverrideModule -> GamlUiModule
  while locating LanguageRegistrar

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
BuiltinGlobalScopeProvider:             "msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider"
CrossReferenceTemplateVariableResolver: "org.eclipse.xtext.ui.editor.templates.CrossReferenceTemplateVariableResolver"
GamlRuntimeModule:                      "msi.gama.lang.gaml.GamlRuntimeModule"
GamlUiModule:                           "msi.gama.lang.gaml.ui.GamlUiModule"
LanguageRegistrar:                      "org.eclipse.xtext.ui.codetemplates.ui.registry.LanguageRegistrar"
MethodBasedModule:                      "org.eclipse.xtext.service.MethodBasedModule"
Modules$OverrideModule:                 "com.google.inject.util.Modules$OverrideModule"
XtextTemplateContextType:               "org.eclipse.xtext.ui.editor.templates.XtextTemplateContextType"
XtextTemplateContextTypeRegistry:       "org.eclipse.xtext.ui.editor.templates.XtextTemplateContextTypeRegistry"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:568)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:190)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at ummisco.gama.ui.modeling.internal.ModelingActivator.createInjector(ModelingActivator.java:104)
	... 115 more
Caused by: java.lang.NullPointerException: Cannot invoke "msi.gaml.descriptions.ModelDescription.getAllSpecies(java.util.List)" because "<local0>" is null
	at msi.gaml.types.Types.getBuiltInSpecies(Types.java:363)
	at msi.gaml.compilation.GAML.getAllVars(GAML.java:417)
	at msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider.lambda$0(BuiltinGlobalScopeProvider.java:184)
	at ummisco.gama.dev.utils.DEBUG.TIMER(DEBUG.java:166)
	at msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider.<init>(BuiltinGlobalScopeProvider.java:172)
	at msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider$$FastClassByGuice$$334702624.GUICE$TRAMPOLINE(<generated>)
	at msi.gama.lang.gaml.scoping.BuiltinGlobalScopeProvider$$FastClassByGuice$$334702624.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:84)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1100)
	at org.eclipse.xtext.ui.editor.templates.XtextTemplateContextTypeRegistry.registerContextTypes(XtextTemplateContextTypeRegistry.java:47)
	at org.eclipse.xtext.ui.editor.templates.XtextTemplateContextTypeRegistry.<init>(XtextTemplateContextTypeRegistry.java:40)
	at org.eclipse.xtext.ui.editor.templates.XtextTemplateContextTypeRegistry$$FastClassByGuice$$289769395.GUICE$TRAMPOLINE(<generated>)
	at org.eclipse.xtext.ui.editor.templates.XtextTemplateContextTypeRegistry$$FastClassByGuice$$289769395.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	... 120 more
```

**Comment by lesquoyb** [comment]
About the plugins causing this problem, it's all of them apart from: `UML`, `Markdown` and the three `Easy shell` related plugins (also `GAMR` but it has been removed from the available plugins now)

**Comment by lesquoyb** [comment]
**Update**
two other plugins can be installed without breaking gama: `git integration for Eclipse` and `Graphical_modeling`.
`Graphical_modeling` is a bit special because it was on a different repository than experimental and thus was not recompiled since a long time, maybe the solution lies somewhere there

**Comment by lesquoyb** [comment]
**another update**
After recompiling `Graphical_modeling`, it turns out that it still works with gama, so that's not what made the difference

**Comment by AlexisDrogoul** [comment]
An interesting related(?) piece of discussion here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=542706

1) `org.eclipse.update.configurator`, a plugin present in the product of GAMA, has been deprecated 10 years ago and is not supported anymore. It may lead to problems in update mechanisms if used together with p2
2) `dropins` seem to be finally an accepted way of updating applications manually (@RoiArthurB )

I will remove the plugin from the product and we'll what happens !

**Comment by AlexisDrogoul** [comment]
Hi,

I've done some experiments and it appears that the current state of GAMA has to deal with a quite different (and maybe easier) problem than the one exposed in this thread so far. 

At least on macOS, the plugins are perfectly loaded and recognised by GAMA once they have been installed. Models are loaded, etc. I tried with different ones, and they all are recognised as plugins. 

However, as mentioned by @lesquoyb, none of the additions to the language seem to work (see image where the webcam plugin is loaded, but none of its primitives are recognised).
![WebcamUsage gaml - Gama 2023-03-12 00-19-26](https://user-images.githubusercontent.com/579256/224503282-48eff756-9e1f-44ec-9537-10a95782bcd6.png)

Digging about what could explain this, I managed to catch these errors when loading GAMA:
![Image 2023-03-12 00-16-50](https://user-images.githubusercontent.com/579256/224503296-4d0e0be1-3403-484f-9194-8f1d326af368.png)
This means that the additions (the GamlAdditions file) are simply not found by GAMA. And they are not found, as far as I can tell, because **they are not present in the plugin**:
![Image 2023-03-12 00-37-33](https://user-images.githubusercontent.com/579256/224503399-f3160845-8a57-476f-9e18-1193f900956a.png)

How come `gaml` is not present in these jars ? (I verified, and in Eclipse the `gaml` folder is correctly produced in `bin`. 

Any explanation welcome !

**Comment by RoiArthurB** [comment]
I saw that the `build.properties` from the QRCode plugin doesn't add the folder `gaml` in `bin.includes` (inspired by [this issue](https://github.com/gama-platform/gama.experimental/issues/22) ), but it doesn't add anything in the jar after compiling :/ 

Still digging... @hqnghi88 any idea ?

**Comment by hqnghi88** [comment]
@RoiArthurB it means some infos are still missing somewhere, i cant make a build local on experimental repo now, but if you can, it seems easy to compare these config with any others completed plugin.

**Comment by AlexisDrogoul** [comment]
What the build.properties is complaining about is the absence of `gaml` for the source builds. Not the binary ones. 

Just one question : is the annotation processor active and mobilised when the plugins are compiled in `experimental` ?

**Comment by RoiArthurB** [comment]
Just to document a bit the solution: it isn't perfectly clear what was causing the issue, but it was an issue from `ummisco.gama.annotations` which wasn't creating the `gaml` folder (needed as pointed previous by Alexis) at the good place.

The solution to this issue has been to add all the same configuration to the plugin `tycho-compiler-plugin` as the one in `msi.gama.parent` in this folder :)
