### ISSUE TITLE
Points of LinearRing do not form a closed linestring when parallel = true

### ISSUE THREAD

**Issue by hqnghi88** [gama-platform/gama.old#3639]
**Describe the bug**
Launch this model
```gaml
model NewModel
global { 
	init{ 
		create ss number:100;
	}
}
species ss skills:[moving] parallel:true{
	geometry shape<-circle(2#m)+1000;
	reflex ssss{
		do wander;
	}
	reflex s{ 
		save ss to:"../results/ss.geojson"+int(self)+machine_time type: "json" ;
	}
}
experiment main{
	output{ 
	}
} 
```

Soon it will throw the exception in gama and eclipse console:
```
java.lang.IllegalArgumentException: Points of LinearRing do not form a closed linestring
	at org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:91)
	at org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:86)
	at org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:380)
	at org.locationtech.jts.geom.util.GeometryEditor$CoordinateSequenceOperation.edit(GeometryEditor.java:326)
	at org.locationtech.jts.geom.util.GeometryEditor.editInternal(GeometryEditor.java:159)
	at org.locationtech.jts.geom.util.GeometryEditor.edit(GeometryEditor.java:132)
	at org.locationtech.jts.geom.util.GeometryEditor.editPolygon(GeometryEditor.java:177)
	at org.locationtech.jts.geom.util.GeometryEditor.editInternal(GeometryEditor.java:151)
	at org.locationtech.jts.geom.util.GeometryEditor.edit(GeometryEditor.java:132)
	at org.locationtech.jts.geom.GeometryFactory.createGeometry(GeometryFactory.java:662)
	at msi.gama.metamodel.topology.projection.Projection.inverseTransform(Projection.java:144)
	at msi.gaml.statements.SaveStatement.buildFeature(SaveStatement.java:488)
	at msi.gaml.statements.save.GeoJSonSaver.internalSave(GeoJSonSaver.java:49)
	at msi.gaml.statements.save.AbstractShapeSaver.internalSave(AbstractShapeSaver.java:123)
	at msi.gaml.statements.save.AbstractShapeSaver.save(AbstractShapeSaver.java:106)
	at msi.gaml.statements.save.AbstractShapeSaver.save(AbstractShapeSaver.java:61)
	at msi.gaml.statements.SaveStatement.privateExecuteIn(SaveStatement.java:368)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.architecture.reflex.ReflexStatement.privateExecuteIn(ReflexStatement.java:90)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:46)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:112)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:499)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:206)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:242)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:570)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.lambda$0(ParallelAgentStepper.java:39)
	at msi.gama.runtime.concurrent.AgentSpliterator.forEachRemaining(AgentSpliterator.java:77)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:37)
	at msi.gama.runtime.concurrent.ParallelAgentStepper.executeOn(ParallelAgentStepper.java:1)
	at msi.gama.runtime.concurrent.ParallelAgentRunner.compute(ParallelAgentRunner.java:140)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Adding exception 1 occurence in ss31 at cycle 31: Java error: illegal argument
in Simulation 0
in save ss to: ('../results/ss.geojson' + int(self)) + machine_time type: json ;
IllegalArgumentException: Points of LinearRing do not form a closed linestring
org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:91)
org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:86)
org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:380)
org.locationtech.jts.geom.util.GeometryEditor$CoordinateSequenceOperation.edit(GeometryEditor.java:326)
org.locationtech.jts.geom.util.GeometryEditor.editInternal(GeometryEditor.java:159)
org.locationtech.jts.geom.util.GeometryEditor.edit(GeometryEditor.java:132)
org.locationtech.jts.geom.util.GeometryEditor.editPolygon(GeometryEditor.java:177)
in save ss to: ('../results/ss.geojson' + int(self)) + machine_time type: json ;
in agent ss31
```

Knowing that the geometry shape<-circle(2#m)+1000; create a gross shape but it is assumed to have in case of the number of agents is NOT big enough, this error will occurs randomly. 

Git version.

**Comment by AlexisDrogoul** [comment]
> Knowing that the geometry shape<-circle(2#m)+1000; create a gross shape but it is assumed to have in case of the number of agents is big enough, this error will occurs randomly.

I'm sorry but I do not understand this sentence ... 🤔

**Comment by hqnghi88** [comment]
Sorry, my english. In fact, i am not sure about the logic to reproduce this issue:
- It is random.
- The frequency of occurs is randomized.
So with my tests (20+ times in each case), the one reproduce more often is the model which have species with gross shape (lot of vertices), so i place a +1000 (buffer) to shape.
It occurs also with simple shape (triangle, square) but with a big enough number of agents (10000+).
AND it seems to be a problem with parallelism (only with parallel: true)

**Comment by ptaillandier** [comment]
There is no real solution for this problem: as each agent at each simulation step saves the geometry of each agent and as this geometry is modified by each agent - and this in parallel - there is no way to be sure that the geometries have not been modified at the very moment of saving and that one of the coordinate list is no longer consistent. In terms of modeling, it doesn't really make sense for each agent to save the geometry of each agent at each time step. Just put the reflex "s" back into the global and there are no more error. Maybe this type of case should be documented in the documentation.

**Comment by hqnghi88** [comment]
Hi,
Just to clarify, I make a save as there is no streaming request in normal gama, but in server mode, there are always the case that any client can request anything at the same time.

**Comment by AlexisDrogoul** [comment]
@hqnghi88 yes, but the point made by @ptaillandier (and me in #3626) is that we cannot expect the structures to always be thread safe and we have absolutely no possibility to solve all the synchronization and concurrent accesses in advance. 
So the solution is to document this : for instance, a request made from outside can perfectly become an action of the global model, which remains synchronised with the different populations, instead of being handled by an agent... The point is to provide some simple solutions where it is safe to make asynchronous calls.

**Comment by hqnghi88** [comment]
I do agree on that, thank you anyway as it is now definitely not my bad implementation in server mode about gis. So i have to test some other solution.
