### ISSUE TITLE
'Status refresh' has encountered a problem with batch experiment

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3667]
**Describe the bug**
Sometimes when running batch experiment I have this error message poping:
![image](https://user-images.githubusercontent.com/6374469/224961860-8f2ec18d-25c9-4891-b6bc-0aae2c896544.png)
Then the status bar stays frozen until I restart gama.
Here is the full error stack from eclipse:
```
java.lang.NullPointerException: Cannot invoke "msi.gama.kernel.experiment.ITopLevelAgent.getName()" because "agent" is null
	at msi.gama.kernel.simulation.SimulationClock.getInfo(SimulationClock.java:306)
	at ummisco.gama.ui.controls.StatusControlContribution.appendPopupTextFor(StatusControlContribution.java:225)
	at ummisco.gama.ui.controls.StatusControlContribution.getPopupText(StatusControlContribution.java:208)
	at ummisco.gama.ui.controls.Popup2.createContents(Popup2.java:112)
	at ummisco.gama.ui.controls.Popup2.updateContents(Popup2.java:146)
	at ummisco.gama.ui.controls.Popup2.display(Popup2.java:213)
	at ummisco.gama.ui.controls.StatusControlContribution.updateWith(StatusControlContribution.java:323)
	at ummisco.gama.ui.controls.StatusControlContribution.updateWith(StatusControlContribution.java:1)
	at ummisco.gama.ui.utils.ThreadedUpdater.runInUIThread(ThreadedUpdater.java:94)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:148)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at msi.gama.application.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**To Reproduce**
For me it happened when running this model, but I guess it really depends on your computer:
```
/**
* Name: NewModel
* Based on the internal empty template. 
* Author: baptiste
* Tags: 
*/


model shelling_exploration


global {
	//Different colors for the group
    list colors <- [rgb ("yellow"), rgb ("red"), rgb ("blue"), 
    	rgb ("orange"), rgb ("green"), rgb ("pink"), rgb ("magenta") , rgb ("cyan")
    ] of: rgb;

	
	//Number of groups
	int number_of_groups <- 2 max: 8 parameter: "Number of groups:" category: "Population";
	//Density of the people
	float density_of_people <- 0.7 parameter: "Density of people:" category: "Population" min: 0.01 max: 0.99;
	//Percentage of similar wanted for segregation
	float percent_similar_wanted <- 0.5 min: float (0) max: float (1) parameter: "Desired percentage of similarity:" category: "Population";
	//Dimension of the grid
	int dimensions <- 40 max: 400 min: 10 parameter: "Width and height of the environment:" category: "Environment";
	//Neighbours distance for the perception of the agents
	int neighbours_distance <- 2 max: 10 min: 1 parameter: "Distance of perception:" category: "Population";
	//Number of people agents
	int number_of_people <- 0;
	//Number of happy people
	int sum_happy_people <- 0 update: all_people count (each.is_happy);
	//Number of similar neighbours
	int sum_similar_neighbours <- 0 update: sum (all_people collect each.similar_nearby);
	//Number of neighbours
	int sum_total_neighbours <- 1 update: sum (all_people collect each.total_nearby) min: 1;
	//List of all the places
	list<space> all_places ;
	//List of all the people
	list<base> all_people;  
	//List of all the free places
	list<space> free_places ;
	
	//Shape of the world
	geometry shape <- square(dimensions);
	
	

	//Initialization of the model
	init {
		//Initialization of the places
		do initialize_places;
		//Computation of the number of people according to the density of people
		number_of_people <- int( length (all_places) * density_of_people);
		//Initialization of the people
		do initialize_people;
	}
	
	
	//Action to initialize the people agents
	action initialize_people { 
		create people number: number_of_people; 
		all_people <- people as list ;  
	} 
	//Action to initialize the places
	action initialize_places { 
		all_places <- shuffle (space);
		free_places <- all_places;  
	} 
}

//Species base representing the people agents
species base {
	rgb color;
	//List of all the neighbours agents
	list<base> my_neighbours;
	//computation of the similar neighbours
	int similar_nearby -> 
		(my_neighbours count (each.color = color))
	;
	//Computation of the total neighbours nearby
	int total_nearby -> 
		length (my_neighbours)
	;
	//Boolean to know if the agent is happy or not
	bool is_happy -> similar_nearby >= (percent_similar_wanted * total_nearby ) ;
}




//Grid to discretize space, each cell representing a free space for the people agents
grid space width: dimensions height: dimensions neighbors: 8 use_regular_agents: false frequency: 0{
	rgb color  <- #black;
}

//Species representing the people agents
species people parent: base  {
	//Color of the people agent
	rgb color <- colors at (rnd (number_of_groups - 1));
	//List of all the neighbours of the agent
	list<people> my_neighbours -> people at_distance neighbours_distance ;
	//Cell representing the place of the agent
	space my_place;
	init {
		//The agent will be located on one of the free places
		my_place <- one_of(free_places);
		location <- my_place.location; 
		//As one agent is in the place, the place is removed from the free places
		free_places >> my_place;
	} 
	//Reflex to migrate the people agent when it is not happy 
	reflex migrate when: !is_happy {
		//Add the place to the free places as it will move to another place
		free_places << my_place;
		//Change the place of the agent
		my_place <- one_of(free_places);
		location <- my_place.location; 
		//Remove the new place from the free places
		free_places >> my_place;
	}
	
}


experiment explo type:batch until:cycle>50 repeat:4 parallel:4{
	
	parameter "nb groups" var:number_of_groups min:2 max:8;
	
	method exploration;
	
	
	permanent {
		display Comparison background: #white {
			chart "Number of happy people" type: xy {
				data "Groups "  value:{number_of_groups, simulations mean_of (each.sum_happy_people)} ;
				
			}
		}
	}
		
}

```

**Expected behavior**
No error message, no status bar freeze

**Comment by lesquoyb** [comment]
Didn't encounter the problem again since then
