### ISSUE TITLE
Headless mode raises an exception

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3689]
**Describe the bug**
When running headless on the latest release (on windows) this error messages appears:
```java.awt.AWTException: headless environment
        at java.desktop/java.awt.Robot.checkHeadless(Robot.java:179)
        at java.desktop/java.awt.Robot.<init>(Robot.java:96)
        at ummisco.gaml.extensions.image.SnapshotMaker.<init>(SnapshotMaker.java:53)
        at ummisco.gaml.extensions.image.SnapshotMaker.getInstance(SnapshotMaker.java:204)
        at ummisco.gaml.extensions.image.Activator.start(Activator.java:37)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
        at org.eclipse.osgi.container.Module.doStart(Module.java:605)
        at org.eclipse.osgi.container.Module.start(Module.java:468)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:500)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
        at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$10(GamaBundleLoader.java:464)
        at ummisco.gama.dev.utils.DEBUG.TIMER_WITH_EXCEPTIONS(DEBUG.java:189)
        at msi.gaml.compilation.kernel.GamaBundleLoader.preBuild(GamaBundleLoader.java:454)
        at msi.gaml.compilation.kernel.GamaBundleLoader.lambda$0(GamaBundleLoader.java:213)
        at ummisco.gama.dev.utils.DEBUG.TIMER(DEBUG.java:166)
        at msi.gaml.compilation.kernel.GamaBundleLoader.preBuildContributions(GamaBundleLoader.java:185)
        at msi.gama.common.Activator.start(Activator.java:28)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
        at org.eclipse.osgi.container.Module.doStart(Module.java:605)
        at org.eclipse.osgi.container.Module.start(Module.java:468)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
        at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at msi.gama.headless.runtime.Application.start(Application.java:330)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
        at org.eclipse.core.launcher.Main.main(Main.java:44)
```

The simulation is executed without any problem though.

**To Reproduce**
1. Try to run anything in headless

**Comment by AlexisDrogoul** [comment]
Yeah. Actually the exception is caught and its stack trace was just written on purpose to signify that snapshots were not available in headless mode, but it is maybe a bit scary :)

I will replace it by a nice sentence !

**Comment by RoiArthurB** [comment]
Tested and works well :)

```
$ bash gama-headless.sh samples/roadTraffic.xml ./out
******************************************************************
* GAMA version 1.9.0                                             *
* http://gama-platform.org                                       *
* (c) 2007-2023 UMI 209 UMMISCO IRD/SU & Partners                *
******************************************************************
> GAMA: version 1.9.0                                   loading on____ linux 6.2.8-arch1-1, x86_64, JDK 17.0.6
> JAI : ImageIO extensions                              loaded for____ |jpg|tiff|bmp|gif|arx|tf8|TF8|png|ppm|jp2|tif|TIF|asc|TIFF|btf|BTF|pgm|wbmp|jpeg|pbm
> GAMA: Plugin msi.gama.core                            loaded in_____ 692ms
> GAMA: Plugin espacedev.gaml.extensions.genstar        loaded in_____ 7ms
> GAMA: Plugin irit.gaml.extensions.database            loaded in_____ 16ms
> GAMA: Plugin miat.gaml.extensions.pedestrian          loaded in_____ 22ms
> GAMA: Plugin msi.gama.headless                        loaded in_____ 3ms
> GAMA: Plugin msi.gama.lang.gaml                       loaded in_____ 7ms
> GAMA: Plugin msi.gaml.architecture.simplebdi          loaded in_____ 88ms
> GAMA: Plugin msi.gaml.extensions.fipa                 loaded in_____ 14ms
> GAMA: Plugin simtools.gaml.extensions.physics         loaded in_____ 17ms
> GAMA: Plugin simtools.gaml.extensions.traffic         loaded in_____ 44ms
> GAMA: Plugin ummisco.gama.network                     loaded in_____ 5ms
> GAMA: Plugin ummisco.gama.serialize                   loaded in_____ 6ms
> GAMA: Snapshot services                               inactive______ (headless mode)
> GAMA: Plugin ummisco.gaml.extensions.image            loaded in_____ 7ms
> GAMA: Plugin ummisco.gaml.extensions.maths            loaded in_____ 85ms
> GAMA: Plugin ummisco.gaml.extensions.stats            loaded in_____ 34ms
> GAMA: Loading extensions to 'create'                  done in_______ 5ms
> GAMA: Loading extensions to 'save'                    done in_______ 108ms
> GAMA: Loading extensions to 'draw'                    done in_______ 3ms
> GAMA: Loading extensions to 'event'                   done in_______ 1ms
> GAMA: Gathering built-in models                       done in_______ 2ms
> GAMA: Loading constants                               done in_______ 79ms
> GAML: Plugins with language additions                 loaded in_____ 2359ms
GAMA configuring and loading...
> GAML: Initializing parser                             done in_______ 796ms
> GAMA: GAML artefacts                                  built in______ 85ms
```
