### ISSUE TITLE
Problem when displaying fields < {3,3} with the "smooth" facet 

### ISSUE THREAD

**Issue by ptaillandier** [gama-platform/gama.old#3776]
**Describe the bug**
When trying to display a (small?) field with the "smooth" facet, an error appears in Eclipse (and nothing is drawn). 

**To Reproduce**
Test the following model:

```
model BugSmallField

global {
	field f <- field(matrix([1],[5]));
}

experiment BugSmallField type: gui {
	output {
		display map type: opengl {
			mesh f  scale:0.1 smooth: true grayscale: true triangulation: true;
		}
		display map_image  {
			graphics "image" {
				draw image(f);
			}
		}
	}
}
```

Error obtained in Eclipse:
Runtime error Index 2 out of bounds for length 2 in OpenGL loop
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at msi.gaml.statements.draw.GaussianBlurMeshSmoothProvider.boxBlurHorizontal(GaussianBlurMeshSmoothProvider.java:88)
	at msi.gaml.statements.draw.GaussianBlurMeshSmoothProvider.smooth(GaussianBlurMeshSmoothProvider.java:39)
	at ummisco.gama.opengl.scene.mesh.MeshDrawer._draw(MeshDrawer.java:165)
	at ummisco.gama.opengl.scene.mesh.MeshDrawer._draw(MeshDrawer.java:1)
	at ummisco.gama.opengl.scene.ObjectDrawer.draw(ObjectDrawer.java:51)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawObjects(LayerObject.java:399)

**Desktop (please complete the following information):**
 - OS: Win 10
 - GAMA version: git 1.9.2

**Additional context**
I tested to display the field by converting it as an image, but nothing is displayed

**Comment by AlexisDrogoul** [comment]
Tested this one again, and fixing #3796 seems to have also fixed it completely.
