### ISSUE TITLE
Issue storing a simulation in HoanKiemAirModel

### ISSUE THREAD

**Issue by Yapper689** [gama-platform/gama.old#3820]
**Describe the bug**
```
1 occurence in Simulation 0 at cycle 4: Java error: ConversionException
in Simulation 0
in write 'Save of simulation : ' + save_simulation('SaveSimu.gsim') ;
ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.RegularEnumSet
converter           : com.thoughtworks.xstream.converters.enums.EnumSetConverter
message[1]          : Could not initialize class com.thoughtworks.xstream.converters.enums.EnumSetConverter$Reflections
converter[1]        : com.thoughtworks.xstream.converters.reflection.SerializableConverter
message[2]          : Unable to make private void java.util.EnumSet.readObject(java.io.ObjectInputStream) throws java.io.InvalidObjectException accessible: module java.base does not "opens java.util" to unnamed module @66ee62dc
converter[2]        : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[3]          : Unable to make field private static final long java.util.EnumSet.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @66ee62dc
-------------------------------
com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:472)
com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:48)
com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
when applying the save_simulation operator on SaveSimu.gsim
in write 'Save of simulation : ' + save_simulation('SaveSimu.gsim') ;
in reflex store_sim when: (time > 0) and every(4 * #cycle)  {
	write ('================ START SAVE + self ' + ' - ') + cycle ;
	write 'Save of simulation : ' + save_simulation('SaveSimu.gsim') ;
	write ('================ END SAVE + self ' + ' - ') + cycle ;
}

in agent Simulation 0
```

**To Reproduce**
[HKAModel.zip](https://github.com/gama-platform/gama/files/11650545/HKAModel.zip)

**Comment by AlexisDrogoul** [comment]
Hi. It seems to be related to https://github.com/microsoft/botbuilder-java/issues/1474

One workaround is to add `--add-opens java.base/java.util=ALL-UNNAMED` to the VM arguments in the `gama.product` (alongside other similar statements in the `Launching` tab). 

Can you try it ? 

-- if you do not run the developper version of GAMA, then you have to add this parameter to the `Gama.ini` file located next the executable

**Comment by Yapper689** [comment]
Thank you for replying! I'm not using the developer version. When I added the parameters, another error occurs:

```
1 occurence in Simulation 0 at cycle 4: Java error: ConversionException
in Simulation 0
in write 'Save of simulation : ' + save_simulation('SaveSimu.gsim') ;
ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : org.eclipse.emf.common.util.URI$URIPool$CachedToString
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private java.lang.Object java.lang.ref.Reference.referent accessible: module java.base does not "opens java.lang.ref" to unnamed module @759ce0c3
-------------------------------
com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:472)
com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:48)
com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
when applying the save_simulation operator on SaveSimu.gsim
in write 'Save of simulation : ' + save_simulation('SaveSimu.gsim') ;
in reflex store_sim when: (time > 0) and every(4 * #cycle)  {
	write ('================ START SAVE + self ' + ' - ') + cycle ;
	write 'Save of simulation : ' + save_simulation('SaveSimu.gsim') ;
	write ('================ END SAVE + self ' + ' - ') + cycle ;
}

in agent Simulation 0
```

**Comment by AlexisDrogoul** [comment]
Since it is almost the same error, have you tried adding almost the same parameter (in addition to the previous one) ? 
i.e. `--add-opens java.base/java.lang.ref=ALL-UNNAMED`

**Comment by Yapper689** [comment]
I tried it and now this error occurs:

```
1 occurence in Simulation 0 at cycle 4: Java error: ConversionException
in Simulation 0
in write 'Save of simulation : ' + save_simulation('SaveSimu.gsim') ;
ConversionException: Failed calling method
---- Debugging information ----
message             : Failed calling method
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : Failed calling method
method              : org.eclipse.emf.ecore.util.EObjectContainmentWithInverseEList.writeObject()
-------------------------------
com.thoughtworks.xstream.core.util.SerializationMembers.callWriteObject(SerializationMembers.java:158)
com.thoughtworks.xstream.converters.reflection.SerializableConverter.doMarshal(SerializableConverter.java:257)
com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
when applying the save_simulation operator on SaveSimu.gsim
in write 'Save of simulation : ' + save_simulation('SaveSimu.gsim') ;
in reflex store_sim when: (time > 0) and every(4 * #cycle)  {
	write ('================ START SAVE + self ' + ' - ') + cycle ;
	write 'Save of simulation : ' + save_simulation('SaveSimu.gsim') ;
	write ('================ END SAVE + self ' + ' - ') + cycle ;
}

in agent Simulation 0
```

**Comment by lesquoyb** [comment]
I tried it on the development version and the saving part seems to work properly now. Though restoring the simulation fails with:
```
java.lang.IllegalArgumentException: Invalid number of points in LineString (found 1 - must be 0 or >= 2)
	at org.locationtech.jts.geom.LineString.init(LineString.java:89)
	at org.locationtech.jts.geom.LineString.<init>(LineString.java:79)
	at org.locationtech.jts.geom.GeometryFactory.createLineString(GeometryFactory.java:621)
	at msi.gama.util.path.GamaSpatialPath.init(GamaSpatialPath.java:192)
	at msi.gama.util.path.GamaSpatialPath.init(GamaSpatialPath.java:1)
	at msi.gama.util.path.GamaPath.<init>(GamaPath.java:82)
	at msi.gama.util.path.GamaSpatialPath.<init>(GamaSpatialPath.java:78)
	at msi.gama.util.path.PathFactory.newInstance(PathFactory.java:69)
	at ummisco.gama.serializer.gamaType.reduced.GamaPathReducer.constructObject(GamaPathReducer.java:77)
	at ummisco.gama.serializer.gamaType.reference.ReferencePath.constructReferencedObject(ReferencePath.java:45)
	at msi.gama.util.IReference.resolveReferences(IReference.java:46)
	at msi.gama.kernel.simulation.SimulationAgent.updateReferences(SimulationAgent.java:1127)
	at msi.gama.kernel.simulation.SimulationAgent.updateWith(SimulationAgent.java:1109)
	at msi.gama.kernel.simulation.SimulationPopulation.initSimulation(SimulationPopulation.java:158)
	at msi.gama.kernel.simulation.SimulationPopulation.createAgents(SimulationPopulation.java:121)
	at msi.gaml.statements.CreateStatement.createAgents(CreateStatement.java:534)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:474)
	at msi.gaml.statements.CreateStatement.privateExecuteIn(CreateStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:47)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.statements.AbstractStatementSequenceWithArgs.privateExecuteIn(AbstractStatementSequenceWithArgs.java:59)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:47)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.metamodel.agent.MinimalAgent.init(MinimalAgent.java:225)
	at msi.gama.kernel.experiment.ExperimentAgent.init(ExperimentAgent.java:371)
	at msi.gama.runtime.ExecutionScope.init(ExecutionScope.java:602)
	at msi.gama.kernel.experiment.ExperimentController.schedule(ExperimentController.java:287)
	at msi.gama.kernel.experiment.ExperimentAgent.schedule(ExperimentAgent.java:418)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:693)
	at msi.gama.kernel.experiment.ExperimentPlan.open(ExperimentPlan.java:748)
	at msi.gama.kernel.experiment.ExperimentController.lambda$2(ExperimentController.java:124)
	at java.base/java.lang.Thread.run(Thread.java:833)
Adding exception 1 occurence in restore_simulation0 at cycle 0: Java error: illegal argument
in restore_simulation0
in action _init_  {
	create simulation from: saved_simulation_file('SaveSimu.gsim') ;
}
```

**Comment by AlexisDrogoul** [comment]
I am going : 
- to solve the "restoring" problem with "xml"
- add a ISaveDelegate to allow saving simulations in different formats ("xml", "binary", "json")

This will hopefully solve this issue  !

**Comment by AlexisDrogoul** [comment]
This issue has actually been solved internally, but not yet pushed as it involves numerous other changes in multiple parts of GAMA.
