### ISSUE TITLE
SVG-based aspect not displayed in 3D displays

### ISSUE THREAD

**Issue by benoitgaudou** [gama-platform/gama.old#3823]
**Describe the bug**
As a follow-up of issue #3822, the SVG-based aspects seem to not being displayed in 3d displays.
The following model (that displays something in 2d), shows a empty white display in 3D.

```
species herd {
	aspect icon {
		draw svg_file("../includes/sheep.svg") size: 100 rotate:45 color: #black;
	}
}

experiment main type: gui {
	output {
		display main_display type: 3d {
			species herd aspect: icon;
		}
	}
}
```

**To Reproduce**
1. Look at the following model.
[Test.zip](https://github.com/gama-platform/gama/files/11683606/Test.zip)

**Expected behavior**
Display of the sheep shape.

**Desktop (please complete the following information):**
 - OS: macOS
 - GAMA version: git, branch 1.8.2

**Additional context**
display 3d only

**Comment by AlexisDrogoul** [comment]
Just to be sure, can you test the experiment `With Inspectors` of model `Ant Foraging.gaml` on your computer ?

**Comment by benoitgaudou** [comment]
I get the ants ...
<img width="1570" alt="Capture d’écran 2023-06-08 à 05 04 42" src="https://github.com/gama-platform/gama/assets/1555274/ec43d422-163a-4a5d-a6a2-ab1c8c55c123">

**Comment by benoitgaudou** [comment]
But when I use the sheep SVG instead of the ant SVG in the `Ant foraging.gaml` model, I cannot see the sheep in 3D display...

**Comment by AlexisDrogoul** [comment]
@benoitgaudou  Please test to see if the latest commit has solved this issue.

**Comment by lesquoyb** [comment]
I tested @benoitgaudou's model and it's still not working:
![image](https://github.com/gama-platform/gama/assets/6374469/cbe082a8-3c37-4d9a-ac10-9113f4c1b93a)
In addition I get this error message in the eclipse console:
```
Runtime error java.lang.NullPointerException: Cannot invoke "msi.gama.metamodel.shape.IShape.getEnvelope()" because the return value of "msi.gama.util.file.GamaGeometryFile.getGeometry(msi.gama.runtime.IScope)" is null in OpenGL loop
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "msi.gama.metamodel.shape.IShape.getEnvelope()" because the return value of "msi.gama.util.file.GamaGeometryFile.getGeometry(msi.gama.runtime.IScope)" is null
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4848)
	at ummisco.gama.opengl.renderer.caches.GeometryCache.getEnvelope(GeometryCache.java:316)
	at ummisco.gama.opengl.OpenGL.getEnvelopeFor(OpenGL.java:1245)
	at ummisco.gama.opengl.scene.ObjectDrawer.applyScaling(ObjectDrawer.java:68)
	at ummisco.gama.opengl.scene.resources.ResourceDrawer._draw(ResourceDrawer.java:80)
	at ummisco.gama.opengl.scene.resources.ResourceDrawer._draw(ResourceDrawer.java:1)
	at ummisco.gama.opengl.scene.ObjectDrawer.draw(ObjectDrawer.java:51)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawObjects(LayerObject.java:399)
	at ummisco.gama.opengl.scene.layers.LayerObject.drawAllObjects(LayerObject.java:381)
	at ummisco.gama.opengl.scene.layers.LayerObject.lambda$2(LayerObject.java:284)
	at ummisco.gama.opengl.OpenGL.compileAsList(OpenGL.java:1390)
	at ummisco.gama.opengl.scene.layers.LayerObject.doDrawing(LayerObject.java:284)
	at ummisco.gama.opengl.scene.layers.LayerObject.draw(LayerObject.java:264)
	at ummisco.gama.opengl.scene.ModelScene.draw(ModelScene.java:138)
	at ummisco.gama.opengl.renderer.helpers.SceneHelper.draw(SceneHelper.java:258)
	at ummisco.gama.opengl.renderer.JOGLRenderer.display(JOGLRenderer.java:210)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:782)
	at ummisco.gama.opengl.view.GamaGLAnimator.lambda$1(GamaGLAnimator.java:166)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at msi.gama.application.Application.start(Application.java:148)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: java.lang.NullPointerException: Cannot invoke "msi.gama.metamodel.shape.IShape.getEnvelope()" because the return value of "msi.gama.util.file.GamaGeometryFile.getGeometry(msi.gama.runtime.IScope)" is null
	at msi.gama.util.file.GamaGeometryFile.computeEnvelope(GamaGeometryFile.java:74)
	at ummisco.gama.opengl.renderer.caches.GeometryCache.lambda$4(GeometryCache.java:316)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 49 more
```

**Comment by lesquoyb** [comment]
I think I understood the reason of some of the problems of svg in windows:
The method `getDocument` in the file `GamaSVGFile.java` was raising an exception that went silent because it was not caught, returning a null document.
If we print the call stack here is the result:
```

java.io.IOException: Unable to make sense of URL for connection
	at org.apache.batik.util.ParsedURLData.openStreamInternal(ParsedURLData.java:515)
	at org.apache.batik.util.ParsedURLData.openStream(ParsedURLData.java:476)
	at org.apache.batik.util.ParsedURL.openStream(ParsedURL.java:440)
	at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:159)
	at ummisco.gaml.extensions.image.GamaSVGFile.getDocument(GamaSVGFile.java:200)
	at ummisco.gaml.extensions.image.GamaSVGFile.fillBuffer(GamaSVGFile.java:471)
	at msi.gama.util.file.GamaGeometryFile.getGeometry(GamaGeometryFile.java:85)
	at msi.gaml.types.GamaGeometryType.staticCast(GamaGeometryType.java:128)
	at msi.gaml.operators.Cast.asGeometry(Cast.java:340)
	at msi.gaml.operators.Cast.asGeometry(Cast.java:355)
	at msi.gama.outputs.display.AWTDisplayGraphics.drawAsset(AWTDisplayGraphics.java:215)
	at msi.gaml.statements.draw.AssetDrawer.executeOn(AssetDrawer.java:73)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:402)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:368)
	at msi.gaml.statements.draw.DrawStatement.privateExecuteIn(DrawStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:47)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:69)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:225)
	at msi.gaml.statements.AspectStatement.privateExecuteIn(AspectStatement.java:1)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:47)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:206)
	at msi.gaml.statements.AspectStatement.executeOn(AspectStatement.java:1)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.outputs.layers.SpeciesLayer.drawPopulation(SpeciesLayer.java:105)
	at msi.gama.outputs.layers.SpeciesLayer.privateDraw(SpeciesLayer.java:73)
	at msi.gama.outputs.layers.AbstractLayer.draw(AbstractLayer.java:110)
	at msi.gama.outputs.display.LayerManager.drawLayersOn(LayerManager.java:176)
	at ummisco.gama.java2d.Java2DDisplaySurface.paintComponent(Java2DDisplaySurface.java:510)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1119)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:952)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedFPScales(RepaintManager.java:1721)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1630)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1570)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1337)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1105)
	at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:75)
	at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:112)
	at java.desktop/java.awt.Container.paint(Container.java:2005)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:890)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:862)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:862)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:835)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1898)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
I locally modified the code of the function to this:
```
	private SVGOMDocument getDocument(final IScope scope) {

		if (document == null) {
			String path = getPath(scope);
			try {
				path = "file:///" + path;
				document = (SVGOMDocument) SVG_FACTORY.createDocument(path);
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
		return document;
	}
```
And it now seems to work, but I don't think it's cross-platform nor will fix everything because the problem is a global incompatibility between the paths in gama and the ones required by batik

**Comment by AlexisDrogoul** [comment]
Thanks. It helped to narrow the issue ! It is not a "global incompatibility", as it works w/o problem on macOS (and probably on Linux), but more a problem with the paths produced / used on Windows and the ones expected by Batik. For instance : https://stackoverflow.com/questions/44536503/batik-url-exception-in-windows . I'll try to follow the workaround they provide there.
