### ISSUE TITLE
Trace statement not working anymore

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3855]
**Describe the bug**
As the title says, the trace statement is not working anymore, it raises a java exception:
```
2 occurrences in 2 agents at cycle 0: Java error: nil value detected
in Simulation 0
in init  {
	trace  {
		int 
	}

}

NullPointerException: Cannot invoke "msi.gaml.compilation.ISymbol.getTrace(msi.gama.runtime.IScope)" because the return value of "msi.gama.runtime.ExecutionScope.getCurrentSymbol()" is null
msi.gama.runtime.ExecutionScope.writeTrace(ExecutionScope.java:444)
msi.gama.runtime.ExecutionScope.setCurrentSymbol(ExecutionScope.java:435)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:53)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:510)
msi.gama.runtime.IScope.execute(IScope.java:440)
msi.gama.runtime.IScope.execute(IScope.java:411)
in agents Simulation 0, a0
```

**To Reproduce**
1. Create a new model containing this code:
```
model tracetest

global {
	init {
		trace{
			int i;
		}
	}
}

experiment a {}
```
3. Run
5. See error

**Desktop (please complete the following information):**
 - GAMA version:1.9.2 release

**Comment by LucasGrjs** [comment]
**Describe the bug**
A close thing happens when we kill a simulation, this exception raise : 

```
java.lang.NullPointerException: Cannot invoke "msi.gama.runtime.IExecutionContext.setCurrentSymbol(msi.gaml.compilation.ISymbol)" because "this.executionContext" is null
	at msi.gama.runtime.ExecutionScope.setCurrentSymbol(ExecutionScope.java:442)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:53)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:518)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:112)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:518)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:206)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:262)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:555)
	at msi.gama.common.interfaces.IScopedStepable.step(IScopedStepable.java:27)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Adding exception  at cycle 0: Java error: nil value detected
NullPointerException: Cannot invoke "msi.gama.runtime.IExecutionContext.setCurrentSymbol(msi.gaml.compilation.ISymbol)" because "this.executionContext" is null
msi.gama.runtime.ExecutionScope.setCurrentSymbol(ExecutionScope.java:442)
msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:53)
msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:518)
msi.gama.runtime.IScope.execute(IScope.java:440)
msi.gama.runtime.IScope.execute(IScope.java:411)
msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:72)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:561)
	at msi.gama.common.interfaces.IScopedStepable.step(IScopedStepable.java:27)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "msi.gama.runtime.IExecutionContext.setCurrentSymbol(msi.gaml.compilation.ISymbol)" because "this.executionContext" is null
	at msi.gama.runtime.ExecutionScope.setCurrentSymbol(ExecutionScope.java:442)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:53)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:59)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:518)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.runtime.IScope.execute(IScope.java:411)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeReflexes(ReflexArchitecture.java:126)
	at msi.gaml.architecture.reflex.ReflexArchitecture.executeOn(ReflexArchitecture.java:112)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:518)
	at msi.gama.runtime.IScope.execute(IScope.java:440)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:206)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:262)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:177)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:555)
	... 6 more
```

**To Reproduce**
Steps to reproduce the behavior:
1. Create a new model containing this code:

```
model kill

global
{
	reflex
	{
		do die;
	}
}

experiment kill{}
```

**Desktop (please complete the following information):**
 - GAMA version:1.9.2 release

**Comment by LucasGrjs** [comment]
Tested both case (trace and do die) and they are working after the fix !
