### ISSUE TITLE
Step doesn't work after stepping back on some models

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama.old#3915]
**Describe the bug**
In some experiment with the record facet set to true, the step function on a simulation works fine, but once the step back function (which works as expected) has been called, it is not possible to step forward again.

**To Reproduce**
1. run this model:
```
model prey_predator

global {
	int nb_preys_init <- 200;
	int nb_predators_init <- 20;
	float prey_max_energy <- 1.0;
	float prey_max_transfer <- 0.1;
	float prey_energy_consum <- 0.05;
	float predator_max_energy <- 1.0;
	float predator_energy_transfer <- 0.5;
	float predator_energy_consum <- 0.02;
	float prey_proba_reproduce <- 0.01;
	int prey_nb_max_offsprings <- 5;
	float prey_energy_reproduce <- 0.5;
	float predator_proba_reproduce <- 0.01;
	int predator_nb_max_offsprings <- 3;
	float predator_energy_reproduce <- 0.5;
	int nb_preys -> {length(prey)};
	int nb_predators -> {length(predator)};
	bool is_batch <- false;

	init {
		create prey number: nb_preys_init;
		create predator number: nb_predators_init;
		write(self);
	}	
	
	reflex stop_simulation when: ((nb_preys = 0) or (nb_predators = 0)) and !is_batch {
		do pause;
	} 
	
	reflex coucou {
	//	int i <- save_simulation("haha.gsim");
	}
}

species generic_species {
	float size <- 1.0;
	rgb color;
	float max_energy;
	float max_transfer;
	float energy_consum;
	float proba_reproduce;
	int nb_max_offsprings;
	float energy_reproduce;
	vegetation_cell my_cell <- one_of(vegetation_cell);
	float energy <- rnd(max_energy) update: energy - energy_consum max: max_energy;

	init {
		location <- my_cell.location;
	}

	reflex basic_move {
		my_cell <- one_of(my_cell.neighbors2);
		location <- my_cell.location;
	}

	reflex eat {
		energy <- energy + energy_from_eat();
	}

	reflex die when: energy <= 0 {
		do die;
	}

	reflex reproduce when: (energy >= energy_reproduce) and (flip(proba_reproduce)) {
		int nb_offsprings <- rnd(1, nb_max_offsprings);
		create species(self) number: nb_offsprings {
			my_cell <- myself.my_cell;
			location <- my_cell.location;
			energy <- myself.energy / nb_offsprings;
		}

		energy <- energy / nb_offsprings;
	}

	float energy_from_eat {
		return 0.0;
	}

	aspect base {
		draw circle(size) color: color;
	}
}

species prey parent: generic_species  {
	rgb color <- #blue;
	float max_energy <- prey_max_energy;
	float max_transfer <- prey_max_transfer;
	float energy_consum <- prey_energy_consum;
	float proba_reproduce <- prey_proba_reproduce;
	int nb_max_offsprings <- prey_nb_max_offsprings;
	float energy_reproduce <- prey_energy_reproduce;

	float energy_from_eat {
		float energy_transfer <- 0.0;
		if(my_cell.food > 0) {
			energy_transfer <- min([max_transfer, my_cell.food]);
			my_cell.food <- my_cell.food - energy_transfer;
		} 			
		return energy_transfer;
	}

	
}

species predator parent: generic_species {
	rgb color <- #red;
	float max_energy <- predator_max_energy;
	float energy_transfer <- predator_energy_transfer;
	float energy_consum <- predator_energy_consum;
	float proba_reproduce <- predator_proba_reproduce;
	int nb_max_offsprings <- predator_nb_max_offsprings;
	float energy_reproduce <- predator_energy_reproduce;

	float energy_from_eat {
		list<prey> reachable_preys <- prey inside (my_cell);
		if(! empty(reachable_preys)) {
			ask one_of (reachable_preys) {
				do die;
			}
			return energy_transfer;
		}
		return 0.0;
	}
}

grid vegetation_cell width: 50 height: 50 neighbors: 4 {
	float max_food <- 1.0;
	float food_prod <- rnd(0.01);
	float food <- rnd(1.0) max: max_food update: food + food_prod;
	rgb color <- rgb(int(255 * (1 - food)), 255, int(255 * (1 - food))) update: rgb(int(255 * (1 - food)), 255, int(255 * (1 - food)));
	list<vegetation_cell> neighbors2 <- (self neighbors_at 2);
}

experiment prey_predator type: gui record:true{
	parameter "Initial number of preys: " var: nb_preys_init min: 0 max: 1000 category: "Prey";
	parameter "Prey max energy: " var: prey_max_energy category: "Prey";
	parameter "Prey max transfer: " var: prey_max_transfer category: "Prey";
	parameter "Prey energy consumption: " var: prey_energy_consum category: "Prey";
	parameter "Initial number of predators: " var: nb_predators_init min: 0 max: 200 category: "Predator";
	parameter "Predator max energy: " var: predator_max_energy category: "Predator";
	parameter "Predator energy transfer: " var: predator_energy_transfer category: "Predator";
	parameter "Predator energy consumption: " var: predator_energy_consum category: "Predator";
	parameter 'Prey probability reproduce: ' var: prey_proba_reproduce category: 'Prey';
	parameter 'Prey nb max offsprings: ' var: prey_nb_max_offsprings category: 'Prey';
	parameter 'Prey energy reproduce: ' var: prey_energy_reproduce category: 'Prey';
	parameter 'Predator probability reproduce: ' var: predator_proba_reproduce category: 'Predator';
	parameter 'Predator nb max offsprings: ' var: predator_nb_max_offsprings category: 'Predator';
	parameter 'Predator energy reproduce: ' var: predator_energy_reproduce category: 'Predator';

	output {
		display main_display {
			grid vegetation_cell border: #black;
			species prey aspect: base;
			species predator aspect: base;
		}

		monitor "Number of preys" value: nb_preys;
		monitor "Number of predators" value: nb_predators;
	}
}
```
3. run a few steps
4. do at least one step backward
5. see that now clicking on the step forward button nothing happens

**Additional context**
The model `Backward Experiment Formats.gaml` in library models works fine.
I don't see any exception in eclipse console while running this in GUI, but in gama server I've seen some exceptions raised sometimes but I don't know if it's related:
```

java.util.zip.ZipException: Not in GZIP format
	at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at ummisco.gama.serializer.implementations.ByteArrayZipper.unzip(ByteArrayZipper.java:66)
	at ummisco.gama.serializer.implementations.SerialisedSimulationRecorder.restore(SerialisedSimulationRecorder.java:106)
	at msi.gama.kernel.experiment.ExperimentAgent.lambda$0(ExperimentAgent.java:938)
	at msi.gama.runtime.GAMA.runAndUpdateAll(GAMA.java:548)
	at msi.gama.kernel.experiment.ExperimentAgent.backward(ExperimentAgent.java:935)
	at msi.gama.headless.core.Experiment.backStep(Experiment.java:137)
	at msi.gama.headless.server.GamaServerExperimentJob.doBackStep(GamaServerExperimentJob.java:103)
	at msi.gama.headless.listener.StepBackCommand.execute(StepBackCommand.java:60)
	at msi.gama.headless.listener.StepBackCommand.execute(StepBackCommand.java:1)
	at msi.gama.runtime.server.CommandExecutor.lambda$1(CommandExecutor.java:118)
	at java.base/java.lang.Thread.run(Thread.java:833)
unable to decode:
java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:376)
	at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1399)
	at ummisco.gama.serializer.implementations.FSTAbstractProcessor.read(FSTAbstractProcessor.java:425)
	at ummisco.gama.serializer.implementations.FSTAbstractProcessor.read(FSTAbstractProcessor.java:1)
	at ummisco.gama.serializer.implementations.AbstractSerialisationProcessor.restoreAgentFromBytes(AbstractSerialisationProcessor.java:38)
	at ummisco.gama.serializer.implementations.SerialisedSimulationRecorder.restore(SerialisedSimulationRecorder.java:106)
	at msi.gama.kernel.experiment.ExperimentAgent.lambda$0(ExperimentAgent.java:938)
	at msi.gama.runtime.GAMA.runAndUpdateAll(GAMA.java:548)
	at msi.gama.kernel.experiment.ExperimentAgent.backward(ExperimentAgent.java:935)
	at msi.gama.headless.core.Experiment.backStep(Experiment.java:137)
	at msi.gama.headless.server.GamaServerExperimentJob.doBackStep(GamaServerExperimentJob.java:103)
	at msi.gama.headless.listener.StepBackCommand.execute(StepBackCommand.java:60)
	at msi.gama.headless.listener.StepBackCommand.execute(StepBackCommand.java:1)
	at msi.gama.runtime.server.CommandExecutor.lambda$1(CommandExecutor.java:118)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.nustaq.serialization.coders.FSTStreamDecoder.readFByte(FSTStreamDecoder.java:329)
	at org.nustaq.serialization.coders.FSTStreamDecoder.readObjectHeaderTag(FSTStreamDecoder.java:122)
	at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:511)
	at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:487)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:446)
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:374)
	... 14 more
```

**Comment by hqnghi88** [comment]
I tried but it seems that it s hard to reproduce, i cant see the exception with combination of random behavior of play, step and stepback

**Comment by hqnghi88** [comment]
https://github.com/gama-platform/gama/assets/6105384/c1cc1191-4589-40e9-ba34-29f2eaa6fe23
